### ISSUE TITLE
Unable to find id of an Agent Token

### ISSUE THREAD

**Issue by daxmc99** [buildkite/docs#1007]
The docs here https://buildkite.com/docs/agent/v3/tokens explain how to create and revoke tokens. 

There is a token I want to revoke however I do not know the id, how can I find the UUID for a specific token in order to revoke it?

**Comment by JuanitoFatas** [comment]
Hello Dax,

You can use the following query from the [GraphQL console](https://buildkite.com/user/graphql/console/8b777e67-8614-47ac-9d4c-03708fb6cc74) to find UUID of agent tokens:

```graphql
query token {
  organization(slug: "Your Organization Slug") {
    agentTokens(first: 100) {
      edges {
        node {
          uuid
          description
        }
      }
    }
  }
}
```

Hope this helps!

**Comment by JuanitoFatas** [comment]
Closing this, feel free to get in touch with support for more questions. Thank you!
