### ISSUE TITLE
Trigger step access control isn’t mentioned

### ISSUE THREAD

**Issue by ticky** [buildkite/docs#102]
It’d be helpful if the trigger step documentation included some mention that the user who starts the triggering build must have access to build in the triggered build.

**Comment by joscha** [comment]
@ticky I think that would be good, yes, I just stumbled over this after I did a quite substantial refactor of our pipeline config, e.g.:

```

2017-08-17 06:13:27 WARN   POST https://agent.buildkite.com/v3/jobs/6b1020ca-37c7-4bfb-a2e0-bf85fd20470a/pipelines: 422 Builds cannot be triggered from this pipeline as there is no Buildkite user linked to this build. Ensure that a user has added "username@users.noreply.github.com" as a verified email address on their account. (Attempt 5/5 Retrying in 1s)
--
  | 2017-08-17 06:13:28 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/6b1020ca-37c7-4bfb-a2e0-bf85fd20470a/pipelines: 422 Builds cannot be triggered from this pipeline as there is no Buildkite user linked to this build. Ensure that a user has added "username@users.noreply.github.com" as a verified email address on their account.
```

The pipeline that build is coming from is part of our private account, so there is no way it would be triggered in the first place if the user wasn't authorized to do so - hence all downstream pipelines are okay to be triggered. Is there a way to instruct BK to trigger that pipeline anyway or use a different method to trigger it?

**Comment by harrietgrace** [comment]
Added in #151 🎉
