### ISSUE TITLE
Do we have any way to get the pipeline reports in email?

### ISSUE THREAD

**Issue by piyush-ranjan-daloopa** [buildkite/docs#1050]
We need a pipeline daily summary at EOD in email. Which can include all the files available on the pipeline page.
![image](https://user-images.githubusercontent.com/83969204/119604335-659b5480-bdde-11eb-98db-17e91f5861e0.png)

Please help

**Comment by plaindocs** [comment]
Hi @piyush-ranjan-daloopa I've passed this idea along to our product team, and will close for now as it isn't really a documentation issue.
