### ISSUE TITLE
update pipeline API not working after migrating with "Convert to YAML steps"

### ISSUE THREAD

**Issue by selvaranjith92** [buildkite/docs#1059]
When we migrated with "Convert to YAML steps" from the "Legacy Steps" we have tried to update the environment variables using the update pipeline API `curl -X PATCH "https://api.buildkite.com/v2/organizations/`. But the changes not reflected to the Buildkite UI. We can't revert it back to "Legacy Steps" that is fine but the update should works properly right.

**Comment by plaindocs** [comment]
Hey @selvaranjith92 

If you're using YAML steps, you can define environment variables using the `env` attribute at the `step` level or at the `pipeline` level.

```yaml
env:
  VAR: value
steps:
  ...
```

There is more info in the [docs](https://buildkite.com/docs/pipelines/environment-variables) and I'll update those to highlight that issue.

**Comment by selvaranjith92** [comment]
Hey @plaindocs 

We are maintaining the buildkite pipelines via buildkite API. So we want to update the YAML Steps using the following buildkite API `curl -X PATCH "https://api.buildkite.com/v2/organizations/`. Can you please tell us, is that possible or not?

As you mentioned the way to define the environment variables, But i'm asking about it's already defined via `curl -X POST "https://api.buildkite.com/v2/organizations/` now we want to update it using `curl -X PATCH "https://api.buildkite.com/v2/organizations/` . So please help us. 

Thanks in advance.
