### ISSUE TITLE
GitHub checks show as pending if blocked_state is omitted

### ISSUE THREAD

**Issue by uozuAho** [buildkite/docs#1065]
The docs indicate that github should show the build/check as passed when there is no `blocked_state` in a block step: https://buildkite.com/docs/pipelines/block-step#block-step-attributes . However, I had to add `blocked_state: passed` to make this happen.

This was in a private repo. I can try to reproduce on a public repo if you need!

**Comment by plaindocs** [comment]
Hey @uozuAho 

Thanks for your patience! That status is configurable in your pipeline settings, I'll update the docs to make that more clear.

![image](https://user-images.githubusercontent.com/95874/143902060-34e064fe-3f0f-4399-bd97-564a206ab4cc.png)
