### ISSUE TITLE
Update AWS Secrets Manager guide for Lambda Scaler IAM Access

### ISSUE THREAD

**Issue by keithduncan** [buildkite/docs#1095]
When I wrote and tested this I didn’t boot a scaling elastic ci stack, instead using a static size of 1 instance. I ensured the instance could boot and read the AWS Secrets Manager Secret via SSM but not that the Lambda scaling function could. The guide docs should be updated with this as a step.

**Comment by plaindocs** [comment]
Closed by #1088
