### ISSUE TITLE
Jobs can be retried only twice through the API call?

### ISSUE THREAD

**Issue by tajo** [buildkite/docs#1106]
Using this call

```
curl -X PUT "https://api.buildkite.com/v2/organizations/{org.slug}/pipelines/{pipeline.slug}/builds/{build.number}/jobs/{job.id}/retry"
```

It works only once and then it returns message that jobs can be retried only twice. 

According to this: https://buildkite.com/docs/pipelines/command-step#retry-attributes, limits should be applied only for automatic retries. Manual always works (at least when triggered through the UI).

**Comment by jayco** [comment]
Hey @tajo good question!

This is expected because that API call is a manual retry so that job can only be retried once. 

If you want to retry the step again, you can use the new job.id returned in that PUT request and retry that.

For example:
```
➜  ~  curl -H "Authorization: Bearer $TOKEN" -X PUT "https://api.buildkite.com/v2/organizations/myorg/pipelines/test/builds/1/jobs/12345678-4895-41b9-aa6a-bb9e25709b5a/retry"
{"id":"5ty67u8i-4895-41b9-aa6a-bb9e25709b5", ... }

➜  ~  curl -H "Authorization: Bearer $TOKEN" -X PUT "https://api.buildkite.com/v2/organizations/myorg/pipelines/test/builds/1/jobs/12345678-4895-41b9-aa6a-bb9e25709b5a/retry"
{
  "message": "Jobs can only be retried once"
}

➜  ~  curl -H "Authorization: Bearer $TOKEN" -X PUT "https://api.buildkite.com/v2/organizations/myorg/pipelines/test/builds/1/jobs/5ty67u8i-4895-41b9-aa6a-bb9e25709b5/retry"
{"id":"09876543-e510-44b7-b73b-cb9a15715116", ....}
```
We will work on getting those docs updated to make that a bit clearer.

**Comment by tajo** [comment]
Ah, this makes a lot of sense. Thanks!
