### ISSUE TITLE
Tweak underline link styles for example repos

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#1147]
Love the new link styles, but maybe for `.Docs__example-repo` sections instead of:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/153/131827640-1dabc04a-6591-440c-bbac-17c5db989c95.png">

it might look better as:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/153/131827617-1f3a9271-9c66-4e02-8dbb-1443fbe179e3.png">

**Comment by plaindocs** [comment]
Definitely! Thanks for spotting.
