### ISSUE TITLE
Hot-reloadable config, or graceful agent restart?

### ISSUE THREAD

**Issue by mallyvai** [buildkite/docs#118]
Hi BK team! 
We're currently evaluating BuildKite to see if it's a good fit for our build-deploy process long-term. It's been a good experience so far, but right now we're in the following situation we need to account for:
1) We have an error or potential security issue with the buildkite-agent.cfg config file / environment config
2) We want to reload the hosts
3) We don't want to interrupt any builds that are in-flight

Right now our only option is to force-stop / start agents en masse, but this runs the risk of killing inflight jobs. 

Is there a mechanism to either

1) Hot-reload the configuration (buildkite-agent.cfg in our case)
2) Be able to issue a command to live running agents to restart and pick up latest settings/environment/etc once the current build they're running has completed?

Thank you!

**Comment by toolmantim** [comment]
Moved to buildkite/agent#476
