### ISSUE TITLE
Width of `cdk diff` command (table) is too narrow

### ISSUE THREAD

**Issue by mcncl** [buildkite/docs#1186]
When running `cdk diff <stackname>` in a pipeline the output of the diff table is far too narrow, making it impossible to read.

The actual json output of changes is fine, but the table itself is seemingly using a fixed with.

![image](https://user-images.githubusercontent.com/10952642/136642958-a1cd085e-70fa-44d0-a2b7-cfe47b4f3133.png)

I'm wondering if I need to pass in a `COLUMNS` environment variable with my command, but I don't know how wide the terminal frame will be, given it will be different depending on machine/display.

**Comment by pzeballos** [comment]
Hi @mcncl! interesting! The CDK's output is designed for interactive terminals and it apparently is doing things our terminal emulation doesn't like :smile:  
It looks like there's a verbose mode that might be less fancy and less broken. Maybe as a workaround, you could try turning it on ("cdk deploy -v") and see if it works. Thanks!
