### ISSUE TITLE
Suggestions to improve docs for docker agent

### ISSUE THREAD

**Issue by thewoolleyman** [buildkite/docs#119]
Hi,

Loving Buildkite.  Originally provided the below info in a ticket, but @keithpitt asked me to open an issue here, so here it is:

----

I had some confusion trying to understand exactly how to properly get an environment hook set up in the docker agent, to ensure my github ssh deploy key and other secrets were properly set for a pipeline which builds and publishes a docker image.

It would be great if there were more of a "step by step" example in the docker agent README for these cases.

At least, it would be good to explain exactly where to stick the environment hook (e.g. ensuring you have mounted `/buildkite/hooks` with your `environment` hook, which can also contain a mechanism to copy your private key to the right place).

Also, I was trying to mount the entire `/buildkite` volume while using the 'stable' image, which didn't work because it blows away the bootstrap.  So, you have to either mount only `/buildkite/hooks` or ensure you use the beta image.

I've documented the steps I took here, feel free to steal from them - below are links to two "Buildkite-specific" sections I have in the notes I took during my setup.  They are a little specific to what I did (on Rancher), but should be a good start on a more detailed step-by-step walkthrough.  They are also to specific commits, so the line numbers don't get stale, but you can look at the latest raw version on master for easier copy-paste.

https://github.com/thewoolleyman/continuous-everything/blame/5a66bb218a2230a36513171ceff0f9e9195ed55f/README.md#L72

https://github.com/thewoolleyman/continuous-everything/blame/5a66bb218a2230a36513171ceff0f9e9195ed55f/README.md#L540

Thanks,
-- Chad

**Comment by toolmantim** [comment]
Thanks for the feedback @thewoolleyman! I've just opened a PR at buildkite/docker-buildkite-agent#57 which integrates your feedback. Could you check that out and let me know if that clarifies things for you? It also includes some other recommendations we've been meaning to add.
