### ISSUE TITLE
Shceduling build

### ISSUE THREAD

**Issue by aparnamane** [buildkite/docs#121]
Hi Team,

wondering how to schedule build using pipeline.yml file.

Thanks,
Aparna

**Comment by sj26** [comment]
Hi @aparnamane,

I'm afraid that, for now at least, scheduled builds can only be configured from within your pipeline's settings on buildkite.com or by [using the GraphQL API](https://building.buildkite.com/tutorial-getting-started-with-graphql-queries-and-mutations-11211dfe5d64). We're still having a think about how this might fit into pipeline.yml. :-)

Cheers,
Sam.
