### ISSUE TITLE
Badge labels

### ISSUE THREAD

**Issue by hobietje** [buildkite/docs#1220]
We use trigger steps to separate our build+test and deploy pipelines.  We would love to be able to update the Status Badge accordingly to say "deploy" (or any other word like "test", "sast", "e2e") rather than "build". E.g.

![image](https://user-images.githubusercontent.com/37542403/139622113-b0ff41ef-bc94-4798-a205-e560dab610ac.png)

**Comment by plaindocs** [comment]
Hi @hobietje 

I've asked our product folks to add that to their backlog. I'll document it once it gets implemented, cheers.
