### ISSUE TITLE
GitHub Enterprise settings screenshots need updating

### ISSUE THREAD

**Issue by waferbaby** [buildkite/docs#1266]
If you look here:

https://buildkite.com/docs/integrations/github-enterprise

The screenshot showing our settings page, here, is out of date now:

![](https://buildkite.com/docs/assets/integrations/github_enterprise/buildkite-github-enterprise-settings-d94b34e9490bbcbae2d6ffbef5d06558c6767bd1923122a16a64bdc1b0fd9f3e.png)

Compare that with the current site:

![image](https://user-images.githubusercontent.com/1027/143142817-8d32f957-3bf3-4d22-b61e-eec8cd5d48ee.png)

cc @karensawrey

**Comment by karensawrey** [comment]
Thanks for the catch, @waferbaby! On it!

**Comment by karensawrey** [comment]
Resolved via #1268.
