### ISSUE TITLE
Support shields.io style badges

### ISSUE THREAD

**Issue by giorgenes** [buildkite/docs#1292]
Currently, the badges return a simple badge in the format " build | status". The "build" text cannot be changed.

It would be great to support changing the text with a param. We want to add multiple badges to our readme page and would like to name the badge with something more meaningful than "build". For example, we might want something like "production build | success", "staging build | failed".

I've tried to achieve this through shields.io but the 2 don't play nicely together (can't customize the colors).

**Comment by karensawrey** [comment]
Hello, @giorgenes! Thank you for raising this issue. This is only a repository for Documentation, but our Support team will be happy to help you - please email your questions to support@buildkite.com.
Cheers!
Karen
