### ISSUE TITLE
Improve hooks/agent config doc: default hook execution directory is not executable

### ISSUE THREAD

**Issue by pfiaux** [buildkite/docs#1302]
Hello,

It might be helpful to others mentioning that the directory the hooks are copied to before execution can be configured through `$TMPDIR` in the agent's environment.

I ran into an issue where my hooks would not execute (Permission denied), it turned out on that particular system `/tmp` was not executable (noexec) and that's where the hooks get copied to. This is briefly mentioned in https://github.com/buildkite/agent/issues/14#issuecomment-41880897 with a similar context.

After looking up the relevant code:
- hook scripts handling https://github.com/buildkite/agent/blob/main/hook/scriptwrapper.go#L86
- tmp file creation https://github.com/buildkite/agent/blob/999464b10bbb698fcd8e018feedcdfbb090264fc/bootstrap/shell/tempfile.go#L17
- tmp folder creation https://pkg.go.dev/os#TempDir

It turned out this can be configured via `$TMPDIR` and making sure that's in the agent's env. I don't think this needs to be fixed in code since it works as expected on most systems, however knowing how to configure it when it doesn't is helpful.

**Comment by karensawrey** [comment]
Hello, @pfiaux! Thank you for reaching out with a useful piece of information!
We'll be adding this info to the Buildkite docs ASAP.
Cheers!

Karen from the Buildkite docs team

**Comment by karensawrey** [comment]
The update was merged into docs (PR #1317). The updated docs page is here: https://buildkite.com/docs/agent/v3/hooks

Many thanks for pointing this out. 

Cheers! Closing the issue.
