### ISSUE TITLE
Replace uses of apt-key with repo signed-by

### ISSUE THREAD

**Issue by keithduncan** [buildkite/docs#1313]
I learned this from a [CloudFlare](https://blog.cloudflare.com/dont-use-apt-key/) post:

> In fact, we found the majority of Debian package repositories on the Internet were providing the same poor guidance: download the GPG key from a website and then either pipe it directly into apt-key or copy it into /etc/apt/trusted.gpg.d/. This method adds the key as a trusted root for software installation from any source. 

It goes on to suggest using the signed-by attribute in the repo source metadata instead.

**Comment by karensawrey** [comment]
Thank you sooooo much, @keithduncan! I'll update the docs!

Cheers, 
Karen

**Comment by plaindocs** [comment]
Fixed by #1339
