### ISSUE TITLE
BUILDKITE_PLUGINS environment variable is undocumented

### ISSUE THREAD

**Issue by amartani** [buildkite/docs#1334]
https://buildkite.com/docs/pipelines/environment-variables documents the values of many of Buildkite's environment variables, but it is missing `BUILDKITE_PLUGINS`.

Note that another page - https://buildkite.com/docs/agent/v3/securing#allowing-a-list-of-plugins - explicitly links to that one as a reference about this variable.

**Comment by plaindocs** [comment]
Thanks for reporting @amartani
