### ISSUE TITLE
Does buildkite have service limits?

### ISSUE THREAD

**Issue by dbanetto** [buildkite/docs#1337]
Hey,

This is more of a question than an issue but, I was wondering if there is any service limits to be aware of around usage like requests per second?

And if there are limits:
* are limits bucketed, by resource, HTTP verb, etc.
* who is the usage counted against, e.g. the org, a user, an api token
* how long after breaching a limits until it returns to normal

This information is really helpful to design a system that will scale with buildkite. Kinda like how you look at a [AWS service quotas](https://docs.aws.amazon.com/singlesignon/latest/userguide/limits.html) to get an idea of how much it can take

**Comment by plaindocs** [comment]
Thanks for raising this issue @dbanetto I'll find out what limits we track an get those documented.

**Comment by plaindocs** [comment]
We'll be working on some new enforced limits over the next couple of months, and won't be able to document anything before that. If you're thinking of doing something specific, I'd suggest dropping our friendly support folks a line on support@buildkite.com with some details about what you're planning.
