### ISSUE TITLE
cctray-for-windows instructions do not work

### ISSUE THREAD

**Issue by botscholar-scott** [buildkite/docs#1341]
https://buildkite.com/docs/integrations/cc-menu#cctray-for-windows

says to add a Feed URL of the form,
https://cc.buildkite.com/[organization-slug].xml?access_token=xxx

and this fails for ours. I tried both https and http (and used a proper access token).

Using cctray 1.8.5 obtained from the link on the above mentioned page.

**Comment by karensawrey** [comment]
Hello, @botscholar-scott! Thank you so much for reaching out! I'll find out what could have gone wrong and update the documentation if necessary. 

Cheers!
Karen, docs writer at Buildkite

**Comment by karensawrey** [comment]
Hello, @botscholar-scott!
After extensive testing, I can confirm that the URL template `https://cc.buildkite.com/[organization-slug].xml?access_token=xxx does` returns the information as expected. Unfortunately, I can also confirm that CCTray for Windows returns an error "Failure to connect to server" when using this URL template. The reason for this is unknown. 

As long as this issue persists, on Windows, you can use an alternative - a [BuildReactor Google Chrome extension](https://buildkite.com/docs/integrations/cc-menu#buildreactor-google-chrome-extension). I hope this helps.

Cheers!
Karen, docs writer at Buildkite

**Comment by botscholar-scott** [comment]
Why would you leave the link to CCtray on the site knowing it doesn't work with your service?
