### ISSUE TITLE
500 error returned when triggering pipeline via /v2/organizations/$ORG/$PIPELINE_SLUG/builds with env var containing "%"

### ISSUE THREAD

**Issue by kayneb** [buildkite/docs#1343]
We've noticed a couple of times now that when triggering a pipeline with your REST API as documented on https://buildkite.com/docs/apis/rest-api/builds#create-a-build that if you provide an environment variable containing a `%` character, the API returns a 500 error with no additional context.

The documentation does not mention any unpermitted characters.

Could you please fix this and/or provide a workaround? Thanks!

**Comment by pzeballos** [comment]
Hi @kayneb!

By default, curl submits a header stating that the request body is [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding#The_application.2Fx-www-form-urlencoded_type), but makes no effort to enforce that on the input side. As you're sending JSON, you'd need to override that header (-H "Content-Type: application/json") to ensure our server accepts it as given, without first incorrectly trying to translate it from the claimed format.
