### ISSUE TITLE
BUILDKITE_SHORT_COMMIT docs missing

### ISSUE THREAD

**Issue by kevinburkesegment** [buildkite/docs#1363]
We apparently are using $BUILDKITE_SHORT_COMMIT environment variable in our Buildkite builds. 

I don't see a reference to that variable on this page, either in the list of environment variables or in the deprecated list: https://buildkite.com/docs/pipelines/environment-variables

**Comment by plaindocs** [comment]
Hi @kevinburkesegment , it looks like that environment variable might be one of yours, set somewhere in your pipeline or build script. Would you mind taking a look and confirming whether that is the case?

**Comment by kevinburkesegment** [comment]
You are correct, sorry about that!

**Comment by plaindocs** [comment]
No worries. :smile_cat:
