### ISSUE TITLE
Meta data docs should include --default flag

### ISSUE THREAD

**Issue by levi** [buildkite/docs#139]
Stumbled upon the incredibly useful --default flag in the source. I wouldn't have been able to successfully use meta-data without it. Would be great to see it reflected in the documentation for others to benefit from it.

**Comment by toolmantim** [comment]
Good catch, and thanks for taking the time to submit the issue! We'll get this fixed.

**Comment by harrietgrace** [comment]
Hey @levi, thanks again for the issue! This is now live in the [meta-data docs](https://buildkite.com/docs/agent/cli-meta-data) 🎉
