### ISSUE TITLE
Buildkite ssh setup doesn't work with AWS ec2 instance

### ISSUE THREAD

**Issue by maximepeabody** [buildkite/docs#1400]
I'm following the instructions here: https://buildkite.com/docs/agent/v3/redhat, and when I try to configure ssh using the "ssh-keygen -t rsa -b 4096 -C "build@myorg.com"" command, I get a permission error. The problem is that I can't su buildkite-agent, because I don't have the buildkite-agent user password. Is there a way around this?

**Comment by plaindocs** [comment]
Hi @maximepeabody, I'm sorry that process isn't clear. 

Would you mind dropping our support folks a line at support@buildkite.com - they will help you sort it out, and then we'll get those docs updated.
