### ISSUE TITLE
Having a GPU CI agent

### ISSUE THREAD

**Issue by RajathSwaroop** [buildkite/docs#1472]
How do I have a GPU buildkite agent using GKE? What are the configuration steps needed for that?

**Comment by pzeballos** [comment]
Hy @RajathSwaroop! We don't have a specific tutorial for GPU, but we have users that set it up with no issue.
You can check out the section in our docs on how to run [the agent on Google Kubernetes Engine](https://buildkite.com/docs/agent/v3/gcloud#running-the-agent-on-google-kubernetes-engine) 

Maybe you can find this example useful: https://github.com/JuliaGPU/buildkite Julia wrote all their experience on configuring Buildkite.

Thanks!
