### ISSUE TITLE
Installing v3

### ISSUE THREAD

**Issue by simontegg** [buildkite/docs#148]
Its unclear how to install v3 from the [Manual installation](https://buildkite.com/docs/agent/installation) instructions.

Specifically, where does the `bootstratp.sh` come from? Or is this relevant to v3

**Comment by harrietgrace** [comment]
Hey @simontegg, thanks for getting in touch, and sorry for the delay! Are you still having issues installing v3? If so, which binary are you using? 
We're in the process of versioning our agent documentation, keep an eye on PR#153 - once that's completed and merged our v3 docs will be live.

**Comment by simontegg** [comment]
Hi @harrietgrace I ended up with a v2 setup that I'm happy with. Thanks fro the headsup about #153.
