### ISSUE TITLE
💄 Side menu is too narrow only on the Webhooks page

### ISSUE THREAD

**Issue by olyism** [buildkite/docs#1487]
How to replicate:
1. Go to the [Webhooks overview page](https://buildkite.com/docs/apis/webhooks) 
1. Resize the browser to around 1024px wide and look at the side menu 👀  the plus icons overlap the text in the menu
1. Resize the browser to around 1440px wide and look at the side menu 👀  the plus icon overlaps the beta badge in Test Analytics
1. Browse to other docs pages and you'll see the widths are different and don't have the aforementioned visual glitches
 
Screenshots:

![Screen Shot 2022-05-11 at 11 23 07 am](https://user-images.githubusercontent.com/7202667/167750233-80dcddc0-0ff8-4b5b-9f59-35a0ba09e0e0.png)

![Screen Shot 2022-05-11 at 11 22 59 am](https://user-images.githubusercontent.com/7202667/167750239-0fe2eb8e-88ea-4329-87d2-fce7371177b2.png)

**Comment by preflightcookie** [comment]
Hey @olyism - I think this specific issue is resolved. Unsure if it was @lachlanhardy 's referenced PR or the nav change but the nav looks right to me now, tested at multiple widths.

<img width="1137" alt="Screen Shot 2022-09-06 at 4 47 22 pm" src="https://user-images.githubusercontent.com/1191571/188566072-19a47f4e-bc6f-483c-b3c6-c3a8688267e4.png">


NB: there is an overflow issue going on in the main body (stay tuned for a PR from me on that one) but it's not impacting the nav at present.

Closing this - feel free to reopen if you can reproduce 👍

**Comment by olyism** [comment]
thanks @preflightcookie. I didn't know this PR existed. Yes this has been resolved with the new sidebar design :)
