### ISSUE TITLE
Matrix expansion does not work for agent keys?

### ISSUE THREAD

**Issue by amscanne** [buildkite/docs#1494]
Not sure if this is a doc gap or a feature request, but I think it is at least a request for doc clarification.

The matrix examples found [here](https://buildkite.com/docs/pipelines/build-matrix#removing-combinations-from-the-build-matrix) are OS and ARCH. However, none of the examples include "{{matrix}}" expansion for the agents parameter for steps. To me at least, this is the obvious use for e.g. ARCH: selecting a worker with a specific architecture to run tests. Instead, the example merely has "echo {{matrix.arch}}" (with no agent preference to run on the given architecture).

However, I can't get the "{{matrix}}" expansion to work on the agent tags at all. Putting aside that this makes the matrix feature much less useful (selecting executors with a specific OS and ARCH is the canonical use for e.g. [GitHub actions matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy)), can this be clarified in the documentation? I would suggest a fix, but I'm not sure what the ground truth is supposed to be. With respect to the actual expansion, if I'm not holding it wrong -- is this planned or is there a canonical bug, etc.?

**Comment by pzeballos** [comment]
Hey! 
According to our docs:
> You can use a Build Matrix to expand a single step into three steps by interpolating the matrix values into [command step](https://buildkite.com/docs/pipelines/command-step) attributes such as [environment variables](https://buildkite.com/docs/pipelines/environment-variables), labels and commands

It's probably not too clear, but that means is only available on those attributes. Interpolation of matrix values inside the `agent` attribute is not supported at the moment.
We are working on expanding the matrix functionality on the rest of the attributes but in the meantime, matrix can be interpolated into these attributes of a command step:

- command
- label
- env

We'll work on adding this clarification to be more specific. Thanks for pointing this out!

**Comment by treykasada** [comment]
@pzeballos Apologies for the ping; I just wanted to know if the expanded matrix support is being tracked publicly somewhere?

I was hoping to request support for matrix templating within a step's `key` field (in order to allow later steps to reference specific expanded steps via `depends_on`), but I can't find any public related GitHub issues to comment on. 😅

**Comment by pzeballos** [comment]
Hi @treykasada! Sorry for the delay! this one fell through the cracks 😅
Unfortunately, we don't have a public place so you can track the status of product requests, but I believe it will be informed in our [changelog](https://buildkite.com/changelog) (and of course, you'll see it reflected in our docs).

Best!
