### ISSUE TITLE
Docs refer to Agent v3 env for BUILDKITE_NO_AUTOMATIC_SSH_FINGERPRINT_VERIFICATION

### ISSUE THREAD

**Issue by lox** [buildkite/docs#154]
The docs refer to `BUILDKITE_NO_AUTOMATIC_SSH_FINGERPRINT_VERIFICATION`, which is only in Agent v3. In Agent v2 it is `BUILDKITE_AUTO_SSH_FINGERPRINT_VERIFICATION `. See https://github.com/buildkite/agent/blob/2b8f1d569b659e07de346c0e3ae7090cb98e49ba/templates/bootstrap.sh#L226

**Comment by harrietgrace** [comment]
@lox Is this the mention in the Agent cli-start doc? I just went to update it, and printed out the `buildkite-agent help start` from a v2 agent, and the `BUILDKITE_NO_AUTOMATIC_SSH_FINGERPRINT_VERIFICATION` appears there too ☹️ 

Do we need to update both the docs and the cli help?

**Comment by lox** [comment]
I think I was getting confused between the bootstrap and the agent. This is fine. It's changed in v3.
