### ISSUE TITLE
Step level branch configuration sample code

### ISSUE THREAD

**Issue by avaly** [buildkite/docs#165]
The https://buildkite.com/docs/pipelines/branch-configuration page should also provide some sample `pipeline.yml` with step-level branch filtering.

**Comment by harrietgrace** [comment]
Hey @avaly, thanks for the suggestion! I'll leave this issue open for now, and will update/close it once extra examples have been added to the docs.
Also, if you have any questions about branch filtering, let me know 😊

**Comment by harrietgrace** [comment]
@avaly a new example is now live 🎉 I also re-wrote some more of the branch configuration doc, so hopefully it's a bit clearer now. https://buildkite.com/docs/pipelines/branch-configuration

I'm going to close this for now, but if you need more examples you're welcome to re-open it!
