### ISSUE TITLE
List of domains that Buildkite agent needs to be able to access

### ISSUE THREAD

**Issue by nick040** [buildkite/docs#166]
I run a Builtkite agent behind an HTTP proxy. The proxy only allows connections to whitelisted domains. Which domains should I have whitelisted for the Buildkite agent to work correctly?

https://agent.buildkite.com
... anything else?

**Comment by harrietgrace** [comment]
Hey @nick040, thanks for getting in touch - sorry to hear you're having problems. The best way to get help on this is to email support@buildkite.com. I'll close this ticket for now, but feel free to re-open it if you need.
