### ISSUE TITLE
Elastic agents 

### ISSUE THREAD

**Issue by somarjun** [buildkite/docs#168]
Hi,

We're trying to implement elastic agents "aws", want to know how exactly the ssh pairing to be done. There is an error occurring when the build is started.

PS:FTA
<img width="1035" alt="screen shot 2017-11-10 at 12 12 42 pm" src="https://user-images.githubusercontent.com/13907369/32641225-e15e2098-c620-11e7-85f1-554b079098bc.png">

**Comment by harrietgrace** [comment]
Hi @somarjun, sorry to hear you're having problems with your ssh pairing!  The best way to get help on this is to email support@buildkite.com. I'll close this ticket for now, but feel free to re-open it if you need 😊
