### ISSUE TITLE
Improve Google Cloud Storage documentation

### ISSUE THREAD

**Issue by buchgr** [buildkite/docs#188]
Hi!

The section on Google Cloud Storage [1] is missing documentation on the below two environment variables (which I found through the agent source code):
* BUILDKITE_GS_ACL
* BUILDKITE_GS_APPLICATION_CREDENTIALS

Also, it doesn't mention that GCS is only supported with agent 3.x.

Thanks!

[1] https://buildkite.com/docs/agent/gcloud#uploading-artifacts-to-google-cloud-storage

**Comment by harrietgrace** [comment]
Hey @buchgr, thanks for the suggestion! I've put those on our list of things to add to the docs 👌🏻
I'm going to leave this open for now, and will update it when they're added.

**Comment by harrietgrace** [comment]
Hi @buchgr, these env vars have been added to the docs so I'm going to close this issue 😊You can check them out here in our Agent v3 Google Cloud doc: https://buildkite.com/docs/agent/v3/gcloud#uploading-artifacts-to-google-cloud-storage

If you have any other questions or requests, you're welcome to reopen this issue or create a new one 🙏🏻
