### ISSUE TITLE
A few environment vars are undocumented

### ISSUE THREAD

**Issue by gittycat** [buildkite/docs#19]
I've noticed that many of the environment variables listed when doing a `buildkite-agent start --help` are not documented here: https://buildkite.com/docs/guides/environment-variables, although the ones I've tried can be queried in the build step.
A useful one is `BUILDKITE_BUILD_PATH`

```
BUILDKITE_AGENT_CONFIG
BUILDKITE_AGENT_DEBUG
BUILDKITE_AGENT_DEBUG_HTTP
BUILDKITE_AGENT_ENDPOINT
BUILDKITE_AGENT_META_DATA
BUILDKITE_AGENT_NO_COLOR
BUILDKITE_AGENT_PRIORITY
BUILDKITE_AGENT_TOKEN
BUILDKITE_BOOTSTRAP_SCRIPT_PATH
BUILDKITE_BUILD_PATH
BUILDKITE_HOOKS_PATH
BUILDKITE_NO_AUTOMATIC_SSH_FINGERPRINT_VERIFICATION
BUILDKITE_NO_COMMAND_EVAL
BUILDKITE_NO_PTY
```

**Comment by toolmantim** [comment]
Hey, thanks for the heads up. Some of these are designed to help the agent communicate with the `bootstrap.sh` script, but we should probably document them in a different section of the doc (as long as they're not internal / expected to change).

**Comment by gittycat** [comment]
Yes, you could do a review of what buildkite-agent start --help puts out and decide on what you want to have public. I personally had a need to figure out the relative path from $BUILDKITE_BUILD_PATH where the repo src code is located. I ended up using this
```
SRC=`pwd | sed 's|'$BUILDKITE_BUILD_PATH'/'$BUILDKITE_AGENT_NAME'/||'`
```

**Comment by harrietgrace** [comment]
Hey @gittycat! 👋🏻It took us a while, but we've finally done a big update to the [env vars doc](https://buildkite.com/docs/pipelines/environment-variables) 😄There was also a recent agent update that cleaned up a bunch of the vars it was displaying too, so everything should be covered now.
