### ISSUE TITLE
GraphQL docs say mention pagination, which doesn't work as expected

### ISSUE THREAD

**Issue by viraptor** [buildkite/docs#190]
https://buildkite.com/docs/graphql-api#relay-compatibility mentions:

> The Buildkite GraphQL API adheres to the Relay Specification, which defines standards for querying paginated collections ("Connections" and "Edges")

The pagination doesn't seem to work though. I can see that the number of builds returned is limited to 500, however the `pageInfo` element never sets `hasNextPage` to true. Even though `BuildConnection.count` is higher than the number of returned edges.

This may be either a lack of documentation about how to handle paging results, or a bug in the implementation.

**Comment by harrietgrace** [comment]
Hey @viraptor, I'm sorry you ran into trouble with this 😔It's definitely a bug, it's just that one connection that doesn't paginate properly. It's on our list to fix it up 👍🏻 
If there's something specific you're trying to get that's over the 500 builds limit, drop us an email at support@buildkite.com and we can help you sort it out. 
I'm going to close this for now, but if you have any other questions, or suggestions for the docs feel free to re-open it.

**Comment by mousavian** [comment]
Hey, any update on this?
I'm Wondering if this is still broken or I am doing sth wrong. :)
