### ISSUE TITLE
Docker config file location incorrect

### ISSUE THREAD

**Issue by creynders** [buildkite/docs#194]
I'm trying to configure a docker agent using a config file, but it seems the documented config file location is incorrect. In the documentation it says to map your config file to `/buildkite/buildkite-agent.cfg`

So I've got the following config file:

```
# file: /devops/buildkite/buildkite-agent.cfg
token="<secret>"
name="docker-test"
meta-data="ci=true,docker=true"
debug=true
```

And spin up a container with:
`docker run -it -v "$HOME/buildkite/buildkite-agent.cfg:/buildkite/buildkite-agent.cfg:ro" buildkite/agent`

It tells me: `2018-03-15 08:29:37 FATAL  Missing token. See: buildkite-agent start --help`

However if I run it detached and docker exec into the container to check the config file, it _is_ correctly mounted, so that doesn't appear to be the problem.
I've also tried running buildkite/agent:3 but the issue persists

**Comment by creynders** [comment]
Obviously I can set the BUILDKITE_AGENT_CONFIG env var to specify the location as a workaround

**Comment by lox** [comment]
Want to drop us an email at support@buildkite.com and we'll assist with troubleshooting @creynders?

**Comment by creynders** [comment]
@lox done! Thanks!

**Comment by sj26** [comment]
Hi @creynders, I think we've covered this in email, but for posterity — it looks like the config location was mis-documented in the README here, it should be `/etc/buildkite-agent/buildkite-agent.cfg`
