### ISSUE TITLE
Agent install docs for 3.0 references `unstable` in repos

### ISSUE THREAD

**Issue by cederberg** [buildkite/docs#218]
This agent install doc: https://buildkite.com/docs/agent/v3/redhat

References: `https://yum.buildkite.com/buildkite-agent/unstable/x86_64/`

But I assume that since 3.0 is now stable, that should be updated. Same thing seem to be the case for most other distros.

**Comment by toolmantim** [comment]
Oh, looks like this was updated in 2189c287a67a7090471bccf522da230a2cf54c46 but never deployed! Thanks for noticing, and taking the time to report it. All fixed now 🙌🏼
