### ISSUE TITLE
“Running multiple agents” documentation should use --spawn

### ISSUE THREAD

**Issue by yonran** [buildkite/docs#2252]
On some platforms, the documentation for “Running multiple agents” recommends starting multiple `buildkite-agent`s using the same config. This was originally written in [2.x](https://buildkite.com/docs/agent/v2/ubuntu) when the default config was `name=%hostname-%n` (`%n` was incremented server-side). But now `%n` does not work anymore ([BuildKite Changelog: Agent names no longer support "%n"](https://buildkite.com/changelog/155-agent-names-no-longer-support-percent-n)) the default config is `name=%hostname-%spawn` (`%spawn` is created client-side https://github.com/buildkite/agent/pull/1377), which requires you to run the agent once with `buildkite-agent --spawn=<n>`. If you run multiple `buildkite-agent` processes with the same config, then “there's potential for the different agent processes to compete for a checkout directory” (https://github.com/buildkite/agent/pull/1389). The following 3 docs should be updated to use `--spawn` instead of running multiple buildkite-agent processes with the same config.

* https://buildkite.com/docs/agent/v3/ubuntu#running-multiple-agents
* https://buildkite.com/docs/agent/v3/debian#running-multiple-agents
* https://buildkite.com/docs/agent/v3/redhat#running-multiple-agents

**Comment by DavidGregory084** [comment]
I suggest fixing this in a slightly different way by using systemd unit file specifiers to give each agent a unique name, rather than whatever `--spawn` does.

However, the docs are still outdated because they encourage users to copy the original unit file to create a template file - the debian packages already contain the template file now.

**Comment by mbelton-buildkite** [comment]
Thanks for raising this @yonran! And thanks for adding your thoughts @DavidGregory084. We've updated the docs to recommend the `spawn` approach for running multiple agents in #2292. 😊
