### ISSUE TITLE
Contradictory statements for Artifact stage

### ISSUE THREAD

**Issue by baank** [buildkite/docs#230]
Referring to this page:
https://buildkite.com/docs/agent/v3/cli-artifact#uploading-artifacts

Within the "Uploading artifacts" section it shows this:
`  $ export BUILDKITE_S3_ACCESS_KEY_ID=xxx
   $ export BUILDKITE_S3_SECRET_ACCESS_KEY=yyy
   $ export BUILDKITE_S3_DEFAULT_REGION=eu-central-1 # default is us-east-1
   $ export BUILDKITE_S3_ACL=private # default is public-read
   $ buildkite-agent artifact upload "log/**/*.log" s3://name-of-your-s3-bucket/$BUILDKITE_JOB_ID
`

But then further down in the "Using your own private AWS S3 bucket" section it says:

"To do so, you’ll need to export the following environment variables using an environment agent hook (this can not be set via the Buildkite web interface, API, or during pipeline upload):"

`export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION="s3://name-of-your-s3-bucket/$BUILDKITE_JOB_ID"
export BUILDKITE_S3_DEFAULT_REGION="eu-central-1" # default: us-east-1
`

Do I need to use an environment agent hook or can I just export variables from the pipeline code ?

**Comment by harrietgrace** [comment]
Thanks for picking that up @baank, and for taking the time to let us know 🙏🏻

In the docs section "Using your own private AWS S3 bucket", I've clarified that there are multiple ways to export the variables, but we recommend using hooks as a best practice. I've also removed the parenthetical about not being able to set the environment variables in some places - I ran some tests just now and they no longer apply 😊
