### ISSUE TITLE
Custom hooks for Buildkite Agent (Docker version) not present

### ISSUE THREAD

**Issue by baank** [buildkite/docs#231]
The documentation for global/build hooks mentions that:
"Each agent installer comes with a hooks directory containing a sample set of hooks"
https://buildkite.com/docs/agent/v3/hooks

But there are no sample hook files with the Docker image:
https://github.com/buildkite/docker-buildkite-agent

**Comment by lox** [comment]
Yup, fair point! The hooks are basically empty scripts, but we can add them to the docker image if that makes things clearer.

**Comment by connaryscott** [comment]
So where are they, can you at least provide a hint on if this is it:

```
 ls /etc/buildkite-agent/hooks/environment 
/etc/buildkite-agent/hooks/environment
```

**Comment by toolmantim** [comment]
@baank we've since updated the docs to be a bit clearer, and moved the repo and it's no longer standalone. So it probably doesn't make any sense to include a sample hooks folder anymore. But if you spot something we can improve, please let us know 🙏🏼

**Comment by toolmantim** [comment]
@connaryscott you can add or mount custom hooks to `/buildkite/hooks` — full docs are here: https://buildkite.com/docs/agent/v3/docker#adding-hooks

The standard Docker image doesn't include any hooks, but if it helps you can the sample ones included in the Linux-based packages here: https://github.com/buildkite/agent/tree/master/packaging/linux/root/usr/share/buildkite-agent/hooks
