### ISSUE TITLE
Docker documentation is in two places

### ISSUE THREAD

**Issue by threeseed** [buildkite/docs#232]
There really should be only one place for official documentation.

For Docker it exists:
https://buildkite.com/docs/agent/v3/docker
https://github.com/buildkite/docker-buildkite-agent

Maybe just move Github docs into your official one ?

**Comment by harrietgrace** [comment]
Yeah totally! It would be great to consolidate those. I'll leave this issue open for now, and update it once we have a plan for how we'd like the Docker docs to be presented.
