### ISSUE TITLE
No mention of artifact_paths on artefact pages

### ISSUE THREAD

**Issue by baank** [buildkite/docs#235]
On the following pages:
https://buildkite.com/docs/builds/artifacts
https://buildkite.com/docs/agent/v2/cli-artifact
https://buildkite.com/docs/pipelines/defining-steps

There is either no mention (first 2 pages) or little mention (last page) of the artifact_paths property for pipelines or really automatic uploading in general.

**Comment by lox** [comment]
Thanks for all the docs issues @baank! I'm sorry if you've had a frustrating time of things. We're going to review them today and see if we can get things a bit more consistent. 

Are you on our Slack channel at https://chat.buildkite.community?
