### ISSUE TITLE
In "Branch Configuration" "Branch pattern examples" with negation are not well documented.

### ISSUE THREAD

**Issue by andreitchaltsev** [buildkite/docs#241]
The doc: https://buildkite.com/docs/pipelines/branch-configuration#branch-pattern-examples
There is one example pattern with negation "!".
It is unclear what happens if there are several positive and negative patterns.

For example, does "A !B C !D" internally mean 
  "A or !B or C or !D" or 
  "!B and !D and (A or C)" or something else?

**Comment by harrietgrace** [comment]
Hey @andreitchaltsev, thanks for letting us know! I'll leave this issue open until the section on negation is clarified 😊

**Comment by harrietgrace** [comment]
Hey @andreitchaltsev! A super delayed response to your original question, but here's some further info about how the negation works with multiple values (if you still need it!):

As soon as there's a value in the `branch` attribute, the builds that include that step will be restricted to the specified branches. Adding more values will expand the set of branches that can include that step. So, with your example, `"branches: A !B C !D"`, only builds on branches A and C will include the step that has this attribute. The addition of `!B` and `!D` doesn't have any effect here, as the pattern is already restricting builds to A and C. 

I'll add this extra info to the branch pattern section. Let me know if there are any further questions you've got about how this works or if there are any other examples you'd like clarified!
