### ISSUE TITLE
Artifacts doc page should mention `--include-retried-jobs` flag

### ISSUE THREAD

**Issue by dewil-official** [buildkite/docs#2512]
Hello! I've been building an automatic retry script for Cypress in our CI, but came across a very odd behavior. Which is that Buildkite successfully downloads all artifacts _**except**_ from the same job, _**if it got retried**_. But that's exactly what I tried to do in my case.

So after many days of debugging and headache, I came across [this ticket](https://github.com/buildkite/agent/issues/1708), which mentions the `--include-retried-jobs` flag and it implies that by default, retried artifacts are discarded. That's unexpected behavior to me and should've been mentioned on the ["Build artifacts" doc page](https://buildkite.com/docs/pipelines/artifacts). It would've saved myself from many hours of debugging.

**Comment by mbelton-buildkite** [comment]
Hi @dewil-official! I'm sorry you had to go through that debugging, but thank you for sharing your findings here. As you suggested, I've raised a PR to include a note about this on the Artifacts page. Let me know if there's anything else you think it should include. 😊

**Comment by mbelton-buildkite** [comment]
I've merged the PR addressing this suggestion in the docs
