### ISSUE TITLE
Block step is always active, would be nice to be inactive until depends_on is complete

### ISSUE THREAD

**Issue by ccoltx** [buildkite/docs#2606]
Good morning. 

There doesn't seem to be any way to configure a block step to wait for the previous step to finish, before becoming active. 

It would be really helpful to be able to configure a block step to be inactive, until it's "depends_on" is completed. Only then can the user confirm and unblock. I'm not advocating that this is how it should be by default, but it would be great, if it could be configured so.

**Comment by jradtilbrook** [comment]
Hi @ccoltx thanks for bringing this up. This isn't an area we are focussing on at the moment but I do have a workaround to achieve a similar effect for you.

You can use a [dynamic pipeline](https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines) to only upload the block step after the "depends_on" step has completed (and the rest of the pipeline after the block step). That way, the block step is not present in the pipeline until after the required step has finished running
