### ISSUE TITLE
Conditional queue assignment

### ISSUE THREAD

**Issue by boboldehampsink** [buildkite/docs#2619]
Hi there,

I couldn't find anywhere in the docs how to conditionally assign a build to a specific queue, i.e. something like

```
agents:
  queue: "dependabot"
  if: "build.author.name == 'dependabot[bot]'"
```

I might've missed this, it might not exist yet or it isn't documented - does anyone know?

**Comment by james2791** [comment]
Hey @boboldehampsink!

Conditional assignment to queues can be done, though its more something that will need to be done _before_ the processing of the build. What I would recommend (and a common way to achieve this) would be to utilise mechanisms such as the [REST](https://buildkite.com/docs/apis/rest-api/builds#create-a-build) or [GraphQL](https://buildkite.com/docs/apis/graphql/schemas/input-object/buildcreateinput) API (setting a `QUEUE` env in either option to then utilise in the pipeline that is triggered (basically it'll expect `QUEUE` to be defined, which can also be defined on the New Build dialog in the UI):

```
agents:
  queue: $QUEUE

steps:
  - label: "Build"
  ...
```

Another way would to export the `QUEUE` environment variable in a [hook](https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks) to then set in a resultant `pipeline upload` - though in this case (like the API example above), the conditional logic will need to happen before a build is attempted to be uploaded with the queue to target.

Hope that helps 😄

**Comment by boboldehampsink** [comment]
@james2791 thanks for the direction. I assume this would then be in a `pre-bootstrap` job hook? I played with it but I can't get this to work. The bash should look something like

```
#!/bin/bash
set -euo pipefail

if [[ "$BUILDKITE_BRANCH" == dependabot* ]]; then
  export QUEUE="dependabot"
fi
```

I just can't wrap my head around how this should work specifically. Any more directions perhaps?

**Comment by boboldehampsink** [comment]
I used that in an environment hook and it looks like it works

**Comment by james2791** [comment]
No worries @boboldehampsink!

The premise was an `environment` hook, but that was is one way about going about it. The way around building something like this would be having an upstream event (like an API `POST`/build env through the UI) set the `QUEUE` - which then set the queue is set at upload time (single `$` interpolation)

i.e for an API build#create (REST) - construct a payload with the `env` key with it being a list of key/value pairs:

```
{
    "commit": "HEAD",
    "branch": "main",
    "message": "A build message",
    "author": {
        "name": "Example User",
        "email": "example_user@this_doesnt_exist.com"
    },
	"env": {
            "QUEUE": "docker-builders"
	}
}
```

Which then the resultant upload of the steps using a setup like above (with `queue: $QUEUE`) will have the env passed through the API set.

Hope that helps!

**Comment by boboldehampsink** [comment]
@james2791 yeahh I'm using the Github integration directly, so not using the API

**Comment by james2791** [comment]
Thats fair @boboldehampsink 👍 

In that case, either the way with said `environment` hook mechanism as that will propagate to the resultant upload(s). If you do [trigger](https://buildkite.com/docs/pipelines/trigger-step#trigger-step-attributes) builds, a similar mechanism can be set there (as in declare `build`.`env` in its YAML - which will be persisted in the triggered build's environment to utilise with any additional uploads
