### ISSUE TITLE
There is no documentation for the allowed-repositories configuration setting

### ISSUE THREAD

**Issue by testworksau** [buildkite/docs#2646]
The `allowed-repositories` configuration setting was added in https://github.com/buildkite/agent/pull/2361 

However, it seems the documentation for this feature was never added:
https://buildkite.com/docs/agent/v3/configuration

The changelog update also refers to `allow-repositories` which causes a bit of further confusion:
https://github.com/buildkite/agent/pull/2411

**Comment by gilesgas** [comment]
Thanks for your query @testworksau . I have created #2648 to address this docs addition.

Would you happen to know what the default value is? I've specified `"none"` (https://github.com/buildkite/docs/pull/2648#discussion_r1485698904) based on my own presumptions but it'd be great if someone could verify this?

Looping in @moskyb for his feedback.

**Comment by gilesgas** [comment]
The PR #2648 has since been merged and hence, closing this issue.
