### ISSUE TITLE
fatal: could not read Password for: terminal prompts disabled

### ISSUE THREAD

**Issue by mdbadiyuzamaevoke** [buildkite/docs#273]
Is there anything that can fix the below issue? Have given all the permissions, connected bitbucket account as well.

  |   | Preparing working directory | 8s
-- | -- | -- | --
  | # Creating "/var/lib/buildkite-agent/builds/ip-172-31-21-45-1/tasko/taskoangular"
  | $ cd /var/lib/buildkite-agent/builds/ip-172-31-21-45-1/tasko/taskoangular
  | $ git clone -v -- https://kirantask@bitbucket.org/kirantask/tasko-project-management-app-front-end.git .
  | Cloning into '.'...
  | fatal: could not read Password for 'https://kirantask@bitbucket.org': terminal prompts disabled
  | # Removing /var/lib/buildkite-agent/builds/ip-172-31-21-45-1/tasko/taskoangular
  | ⚠️ Warning: Checkout failed! Error running `/usr/bin/git clone -v -- https://kirantask@bitbucket.org/kirantask/tasko-project-management-app-front-end.git .`: exit status 128 (Attempt 1/3 Retrying in 2s)
  | # Creating "/var/lib/buildkite-agent/builds/ip-172-31-21-45-1/tasko/taskoangular"
  | $ git clone -v -- https://kirantask@bitbucket.org/kirantask/tasko-project-management-app-front-end.git .
  | Cloning into '.'...
  | fatal: could not read Password for 'https://kirantask@bitbucket.org': terminal prompts disabled
  | # Removing /var/lib/buildkite-agent/builds/ip-172-31-21-45-1/tasko/taskoangular
  | ⚠️ Warning: Checkout failed! Error running `/usr/bin/git clone -v -- https://kirantask@bitbucket.org/kirantask/tasko-project-management-app-front-end.git .`: exit status 128 (Attempt 2/3 Retrying in 2s)
  | # Creating "/var/lib/buildkite-agent/builds/ip-172-31-21-45-1/tasko/taskoangular"
  | $ git clone -v -- https://kirantask@bitbucket.org/kirantask/tasko-project-management-app-front-end.git .
  | Cloning into '.'...
  | fatal: could not read Password for 'https://kirantask@bitbucket.org': terminal prompts disabled
  | # Removing /var/lib/buildkite-agent/builds/ip-172-31-21-45-1/tasko/taskoangular
  | ⚠️ Warning: Checkout failed! Error running `/usr/bin/git clone -v -- https://kirantask@bitbucket.org/kirantask/tasko-project-management-app-front-end.git .`: exit status 128 (Attempt 3/3 Retrying in 2s)
  | 🚨 Error: Error running `/usr/bin/git clone -v -- https://kirantask@bitbucket.org/kirantask/tasko-project-management-app-front-end.git .`: exit status 128

**Comment by aish-kozhisherry** [comment]
Hi! @mdbadiyuzamaevoke how did you resolve it? Am facing the same issue.
"fatal: could not read Password for 'https://***@bitbucket.org': terminal prompts disabled"

**Comment by harrietgrace** [comment]
Hi @mdbadiyuzamaevoke and @aish-kozhisherry, sorry you've run into trouble with your Bitbucket repos! Bitbucket deprecated their old API this week, so we've just pushed out some fixes to the Buildkite/Bitbucket integration. You'll need to reconnect your Bitbucket account to your Buildkite user account so that we've got the latest credentials - that can be done here: https://buildkite.com/user/connected-apps. 

If you're still seeing issues with your Bitbucket repo pipelines after you've reconnected your accounts, shoot through an email to support@buildkite.com and we'll help you sort it out 😊

**Comment by paulwitt** [comment]
@harrietgrace Was this actually resolved?  I'm getting the same error and the clone only works if I include my password (https://username:password@bitbucket.org/org/repo).  How am I supposed to be able to connect to bitbucket without that password?

**Comment by harrietgrace** [comment]
Hey @paulwitt, hmm it should have been! Sorry that you're still having issues with it 😣 Could I get you to shoot through an email to support@buildkite.com? Then we can have a look at your org and see what's going on 👍🏻
