### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by fduran** [buildkite/docs#2849]
In the API page at [https://buildkite.com/docs/apis/rest-api](https://buildkite.com/docs/apis/rest-api)  we see:

```
curl https://api.buildkite.com

{
  "response": "Hello World"
}
```

But response is like:

```
{"message":"🛠","timestamp":1718978204}
```

**Comment by gilesgas** [comment]
Thanks @fduran , this'll be fixed in https://github.com/buildkite/docs/pull/2856
