### ISSUE TITLE
logs for buildkite (pipeline/step runs)

### ISSUE THREAD

**Issue by akhoury-tyro** [buildkite/docs#286]
where does buildkite store it's logs for each pipeline/step that has run? (i.e pipeline name, step name, time step run)

**Comment by akhoury-tyro** [comment]
I have noticed that agents do record when they run jobs:

```
2018-07-23 00:18:06 INFO   Assigned job xxx-xxx-xxx. Accepting...
2018-07-23 00:18:07 INFO   Starting job xxx-xxx-xxx
2018-07-23 00:18:09 INFO   [Process] Process is running with PID: 28
2018-07-23 00:18:28 INFO   Process with PID: 28 finished with Exit Status: 128
2018-07-23 00:18:29 INFO   Finished job xxx-xxx-xxx
```

- Is it typical/default when setting up an agent to write these to a logfile (I expected /var/logs/buildkite-agent.log for example)
- Is there more detail available (pipeline name, commit, script, user etc)

I don't want to write a log script if one already exists, but at this point I'm considering writing an agent hook that runs pre-command to extract this data.

**Comment by lox** [comment]
Hi @akhoury-tyro, the agent outputs logging information like you posted to `stdout`. It's up to the process manager (upstart, initd, systemd, etc) to then write it to a log in the way that makes sense for the operating system. What operating system are you on and how did you install the agent?

In terms of the output of each job run, we don't log that to disk, but you can use tee to write it locally and then store it yourself. Check out https://buildkite.com/docs/builds/managing-log-output#storing-the-original-log.

**Comment by lox** [comment]
Drop us an email at support@buildkite.com if we can assist further!

**Comment by petemounce** [comment]
I went to the trouble to write a golang binary that enriches each build log line with structured data (mostly, the environment variables that buildkite sets), then pumps it into logstash, so it's available within our Elasticsearch/Kibana.

I've been able to use this to:

* notify individuals and teams when there is a flaky test
    * quantify how flaky it is (over the timespan of data that I retain) - this can be used to derive an estimate for engineering hours wasted with retries and debugging, used to justify prioritising fixes where that's not an automatic "oh, yes; of course, we'll fix it since a flaky test is a random number generator" (which is much more normal, here!)
    * identify when it first flaked, with the commit/PR (if that's within the timespan of data that I retain), reducing the engineering hours spent localising the root cause

I hope to open-source this, it's not a large piece of work.

**Comment by lox** [comment]
That sounds really neat @petemounce!
