### ISSUE TITLE
Incorrect description of BUILDKITE_REBUILT_FROM_BUILD_NUMBER

### ISSUE THREAD

**Issue by yaningo** [buildkite/docs#2869]
The description of the [`BUILDKITE_REBUILT_FROM_BUILD_NUMBER` environment variable](https://buildkite.com/docs/pipelines/environment-variables#BUILDKITE_REBUILT_FROM_BUILD_NUMBER) mentions the UUID instead of the number

<img width="798" alt="Screenshot 2024-07-04 at 12 50 47" src="https://github.com/buildkite/docs/assets/15132489/b21d816b-acd4-4bc3-9adc-2e7c45c34ff3">

&nbsp;

It should be:

The **number** of the original build this was rebuilt from or "" if not a rebuild.

**Comment by gilesgas** [comment]
Thanks for spotting this typo @yaningo !
While admittedly the source content to fix this issue would've been a tad tricky in the docs, in future, if you find any problems with the Buildkite Docs you'd like to fix, please feel free to create a PR directly against its repository!
