### ISSUE TITLE
Trigger steps are missing from the Pipelines REST API 

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#290]
Trigger steps are currently missing from the REST API docs (https://buildkite.com/docs/apis/rest-api/pipelines#create-a-pipeline).

Here's an example of the valid params:

```json
{
  "steps": [{
    "type": "trigger",
    "trigger_project_slug": "a-pipeline",
    "trigger_message": "A message",
    "trigger_commit": "HEAD",
    "trigger_branch": "master",
    "trigger_env": {},
    "trigger_async": true
  }]
}
```

The required/options and defaults are the same as the trigger step itself (only the pipeline slug is required):
https://buildkite.com/docs/pipelines/trigger-step

We should really update it to the `pipeline_slug` and not `project_slug` in the backend too.

**Comment by harrietgrace** [comment]
Sounds great! 

@toolmantim is the "manual" type a block step? It would be great to add some more info to that doc around doing block steps too, particularly ones with dialog boxes.

**Comment by toolmantim** [comment]
Yep, "manual" is a block step! But I can't see any way to actually pass through any of the field parameters via the REST API. I don't think that's supported right now.

**Comment by harrietgrace** [comment]
Ah okay! I'll note that the block step fields aren't available then 👍🏻thanks!
