### ISSUE TITLE
annotate command docs may be misleading

### ISSUE THREAD

**Issue by bjeanes** [buildkite/docs#296]
https://buildkite.com/docs/agent/v3/cli-annotate

Last night, I was working on improving some annotation output in a build of mine and had some feedback from the experience.

1. The CLI help output states that that "Annotations can be written in either Markdown or HTML"

    However, it seems that only Markdown is processed and that the few HTML tags that are honoured are the ones that most Markdown processors accept as part of the MD spec. It might be clearer to state that it accepts Markdown, including some HTML tags within the Markdown document.

    An example build where I was trying to upload a .html file and it was clear that it was being processed only via Markdown processor (indented tags treated as code blocks, etc): https://buildkite.com/covidence/app/builds/1652 (the .html file is also an artifact)

2. The usage docs show `<file>` being passed as a parameter. However, when I tried the following, it resulted in an annotation with the file _name_ as the content:

    ``` shell
    gem install brakeman
    brakeman -q -A --no-pager \
      --github-repo covidence/covidence \
      --no-exit-on-warn \
      --no-exit-on-error \
      -f html > brakeman.html
    buildkite-agent annotate brakeman.html --style warning --context brakeman
    ```
   
    I tried with file name before args (as docs show) and after but it didn't appear to make a difference.

    Example build showing the annotation and the .html file as an artifact: https://buildkite.com/covidence/app/builds/1648

3. _(this might belong as a feature request elsewhere instead)_ This may be tricky depending on your Markdown processor and potentially some security headers, but it would be _wonderful_ if I could create an `<iframe>` if and only if it was loading an artifact. That would allow embedding full HTML output for commands which cannot generate Markdown or for which it would be difficult to represent output in Markdown.

**Comment by sj26** [comment]
I think this has been fixed by updating the agent annotate command usage text, and a corresponding update to the docs page:

https://buildkite.com/docs/agent/v3/cli-annotate

🎉

**Comment by sj26** [comment]
> (this might belong as a feature request elsewhere instead) This may be tricky depending on your Markdown processor and potentially some security headers, but it would be wonderful if I could create an <iframe> if and only if it was loading an artifact. That would allow embedding full HTML output for commands which cannot generate Markdown or for which it would be difficult to represent output in Markdown.

This one sounds like a bit difficult for us security-wise. But maybe we could add the ability to link to artifact URLs, and rewrite them for display?

**Comment by toolmantim** [comment]
Yeah, we found this ourselves @bjeanes which led to buildkite/agent#792 and buildkite/agent#792 — but I think the next step was to add a `--html` or `--format html` argument to the annotate command for uploading HTML content.

**Comment by bjeanes** [comment]
> I think the next step was to add a `--html` or `--format html` argument to the annotate command for uploading HTML content.

Seems sane, but would probably still need to be sandboxed in some way to prevent malicious JS from loading or CSS from leaking. It definitely would be handy though!

I think buildkite/agent#813 and the docs update resolves the main reason for this issue though!

**Comment by sj26** [comment]
Yep, I think we'd do similar html santization we do on the markdown content — whitelist tags, disallow js, and whitelist bass classes only, or something.

**Comment by bjeanes** [comment]
> whitelist bass classes only

That is sane, but FWIW that would not have helped me. The problem I'm trying to solve is expose reports from generated tools. I can't generally control the classes they use.

I wonder if there is any reliable way to rewrite a HTML doc to inline all styles. I think I've come across a few tools specifically for doing this with HTML emails. Perhaps applying a similar strategy could be successful... 🤔

**Comment by bjeanes** [comment]
This is what I was thinking of before: https://github.com/Mange/roadie. It's designed to allow you to write "normal" HTML/CSS and it will post-process it to have styles be inlined for maximum mail client compatibility.

Obviously, this is not designed to be a "secure" solution for 3rd party code so I am very much on the side of "it's not worth the feature to risk getting it wrong" but still interesting to consider.

**Comment by ticky** [comment]
The feature isn’t really intended for piping HTML from arbitrary reports into, our UI isn’t built for that. It’s been intended from the start as a way to surface a small amount of useful information, be it some statistics, a link to a particular artifact, or some other clever thing, via a little snippet of markdown.

I do understand wanting to push an HTML report from various tools into this but it’s not really suitable for that - uploading as an artifact and then linking off to the report makes more sense from that perspective. We’ve been pondering ways to make generated HTML reports in particular less clunky (we’ve had countless issues with reports generated with external resources and weird scripting which you can’t really do much other than zip up right now due to the security model of artifacts on s3), but we’re not there yet.

**Comment by bjeanes** [comment]
💯 makes sense. I agree artifact+link is much saner and sufficient.
Fortunately I've been able to get our generate a markdown summary easily
enough in most cases, as i really want certain things visible (e.g.
security report).

Thanks for your time talking it out with me!
