### ISSUE TITLE
UI for a wait step that continues on failure

### ISSUE THREAD

**Issue by kielgillard** [buildkite/docs#301]
I'd like a UI for the YAML under the subheading "Continuing on failure" in the [documentation](https://buildkite.com/docs/pipelines/wait-step).

Could we have a check box (or whatever) in the UI for the wait job step that expresses the intention to continue even if the previous steps failed?

Right now, it seems the only way to implement this is by [uploading YAML files](https://buildkite.com/docs/pipelines/defining-steps) which hides the details of the steps from the web interface, increases the conceptual complexity of the pipeline and increases the risk of error when editing a YAML file by hand should the steps need changing.

**Comment by keithpitt** [comment]
@kielgillard 👋 we hear you! We've got a secret feature that allows you to manage pipelines in the UI by describing them with the same YAML syntax that you use for pipeline uploads. Is that something you'd be interested in testing? You'd be able to define steps with the `continue_on_failure` flag then.

**Comment by kielgillard** [comment]
Turns out, after reconsidering the problem, we didn't need the wait step, so I might pass on testing it. But thank you anyway, I really appreciate it. I'm very suprised though: has there not been any demand for a UI for this kind of step?

**Comment by harrietgrace** [comment]
Hey @kielgillard! Sorry for the delayed reply 😅You got me curious about requests for this feature, so I went and had a look through our support system and github issues - surprisingly, you're the first to ask! We're always keen to hear about different use cases, so thanks for letting us know that it would be useful for you 👌🏻👍🏻

I'm going to close this for now, but definitely shoot us an email at support@buildkite.com if you run into any other issues! 🙏🏻
