### ISSUE TITLE
API Doc: List Teams: Requires more information

### ISSUE THREAD

**Issue by jearley0** [buildkite/docs#3016]
Greetings,

For [https://buildkite.com/docs/apis/rest-api/teams#list-teams](url), there is not a way to pull a list of all teams in an organization unless the API Token was generated from a user that is a member of ALL Teams.

This prevents monitoring of teams, both current and future. Any chance this API could be updated to ensure the list of teams visible to an account within the BuildKite UI is also searchable via the API?

![image](https://github.com/user-attachments/assets/77af9f2e-f233-448e-8067-9b172aabfb56)

**Comment by karensawrey** [comment]
Hello, [jearley0](https://github.com/jearley0)! 
A user who is an Admin on a given Buildkite org will be able to view the list of all Teams on that org by running the [query](https://buildkite.com/docs/apis/rest-api/teams#list-teams) you are referring to using their API Access Token, even the Teams they are not members of, much like in the Buildkite's UI. 

CC: @gilesgas
