### ISSUE TITLE
learngraphql.com links are broken

### ISSUE THREAD

**Issue by wilvk** [buildkite/docs#304]
e.g.
https://buildkite.com/docs/apis/graphql-api

shows:

This site can’t provide a secure connection
learngraphql.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

on Chrome for the link https://learngraphql.com/

**Comment by lox** [comment]
Thanks for the heads-up! Looks like https://graphql.org/learn/ might be the canonical now. We'll update this!
