### ISSUE TITLE
Exit status -1 does not auto-retry by default

### ISSUE THREAD

**Issue by ticky** [buildkite/docs#306]
The command step docs page suggests that jobs with a -1 exit status (Agent lost) are auto-retried by default:

https://github.com/buildkite/docs/blob/d7ca95ea8b7d839c35e1e0311e38737c4f7e2a9e/pages/pipelines/command_step.md.erb#L204-L207

This isn’t the case at all, as far as I can tell; there’s no code path which defines this behaviour anywhere in the app.

**Comment by harrietgrace** [comment]
Ah that's bad times! This bit was added along with all the updates to the retry code in https://github.com/buildkite/docs/pull/185. I'm guessing things have changed since then?

**Comment by lox** [comment]
> By default, we automatically retry on this exit status as well.

I'm not sure that thing ever existed. @keithpitt?

**Comment by keithpitt** [comment]
It's kinda right! The behaviour you identified @ticky happens if you set `retry: true`. So the rule is:

`Jobs that exit with -1 will be automatically retried *if you're turned on retries*`

**Comment by harrietgrace** [comment]
Sweet, I'll add that caveat. Thanks all!

**Comment by lox** [comment]
I was thinking it would be amazing to annotate exit status -1 in the UI with a link to these docs too!

**Comment by ticky** [comment]
Yeah, it’d be great to maybe say `Exit status -1: Agent “${agent.name}” lost.`

**Comment by ticky** [comment]
Perhaps this note should instead frame this as `an exit_status value of “*” will retry jobs whose agents were lost (which have an exit status of -1)` rather than talking directly about the exit status.

**Comment by worxli** [comment]
The log says: `Error: The command exited with status -1`. But then at the bottom of the block it says: `Exited with status 255`.
```
retry:
      automatic:
        exit_status: -1
```
also does not seem to work. Does this need to be 
```
retry:
      automatic:
        exit_status: 255
```
?

**Comment by toolmantim** [comment]
Sorry @worxli! This is something we're on in https://github.com/buildkite/agent/pull/890 and https://github.com/buildkite/agent/pull/899.

At the moment you need to follow the exit code that's in the bottom of the block, not what's in the build output. So for you, you probably want to retry on both `-1` and `255`.

**Comment by harrietgrace** [comment]
This was fixed in https://github.com/buildkite/docs/pull/355 🙌🏻
