### ISSUE TITLE
Team_uuids and default_branch ignored when creating pipelines

### ISSUE THREAD

**Issue by niroliyanage** [buildkite/docs#313]
Hi
The following json doesnt seem to assign the team to the newly created pipeline
<
{
   "name": "bla",
   "description": "Pipeline to create infra for us-qa",
   "repository": "git@bitbucket.org:xxxx/xxxxx",
   "env": {
    "TF_VAR_bucket": "whispir.au.tfstate"
   },
     "provider": {
    "id": "bitbucket",
    "settings": {
      "build_pull_requests": true,
      "pull_request_branch_filter_enabled": false,
      "skip_pull_request_builds_for_existing_commits": true,
      "build_tags": false,
      "publish_commit_status": true,
      "publish_commit_status_per_step": false,
      "repository": "xxxxxx"
    }
    },
    "default_branch" : "us-qa",
   "team_uuids": "3eac013d-f259-4396-9bf1-29ffeae4f82f",
   "branch_configuration": "us-qa",
   "steps": [
    {
      "type": "script",
      "name": ":pipeline:",
      "command": "buildkite-agent pipeline upload .buildkite/create-infra.yml",
      "artifact_paths": "",
      "timeout_in_minutes": null,
      "agent_query_rules": [
        "queue=whispir-infra"
      ],
      "concurrency": null,
      "parallelism": null
    }
  ]
}

>

Regards
NIro

**Comment by harrietgrace** [comment]
Hey @niroliyanage, oh no! Sorry to hear it's not working ☹️If you could send us an email at support@buildkite.com we can help you sort out what's happening 🙏🏻👍🏻
