### ISSUE TITLE
[ci skip] [skip ci] is still triggering builds.

### ISSUE THREAD

**Issue by davetao** [buildkite/docs#315]
Hello,

I have been making commits to a project, pushing it with those two in the commit message. It still triggers a build. I am wondering if i had accidently set it up in a way that would have disabled that feature.

I was following the steps outlined in...
https://buildkite.com/docs/pipelines/ignoring-a-commit

**Comment by harrietgrace** [comment]
Hey @davetao, oh no! Sorry to hear it's not working ☹️If you could send us an email at support@buildkite.com we can help you sort out what's happening 🙏🏻👍🏻
