### ISSUE TITLE
Document that Bitbucket Server doesn't always send commit messages

### ISSUE THREAD

**Issue by lox** [buildkite/docs#317]
We should note in our Build Skipping (e.g `no ci`) stuff that sometimes Bitbucket Server doesn't send commit messages in it's webhooks, so this mechanism is unreliable.

**Comment by harrietgrace** [comment]
From the looks of the Bitbucket webhooks docs, it seems that they send the commit message on a 'push', 'commit_comment_created', 'build_status_created', and 'build_status_updated'. @lox the example that was included in the Helpscout thread that prompted this issue looks like it was a 'refs_changed' event. 

We could list the types of webhooks from Bitbucket that send commit messages in our docs? Would that be helpful?

**Comment by lox** [comment]
> We could list the types of webhooks from Bitbucket that send commit messages in our docs? Would that be helpful?

Yeah, I reckon they would be @harrietgrace!
