### ISSUE TITLE
Agent Environment Docs Needs Love

### ISSUE THREAD

**Issue by enkoder** [buildkite/docs#322]
Turns out you can edit these envars in the environment hooks. 

https://buildkite.com/docs/pipelines/environment-variables

**Comment by lox** [comment]
Thanks for letting us know, we will clarify which of these can be overridden.

**Comment by harrietgrace** [comment]
Hey @enkoder! 👋🏻We've just released a big update to the [env vars doc](https://buildkite.com/docs/pipelines/environment-variables) which included clarifying which vars can be edited in hooks.
