### ISSUE TITLE
Using secure HKP

### ISSUE THREAD

**Issue by adrianke** [buildkite/docs#328]
In the [Ubuntu agent's documentation](https://buildkite.com/docs/agent/v3/ubuntu) the following step is listed:

`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 32A37959C2FA5C3C99EFBC32A79206696452D198`

It should probably use HKPS instead.

**Comment by harrietgrace** [comment]
Thanks @adrianke! 🙏🏻 I'll get that updated 👍🏻
