### ISSUE TITLE
Document how Agent tags work with multiple queues

### ISSUE THREAD

**Issue by lox** [buildkite/docs#333]
It's possible for agents to listen on multiple queues, for example:

`buildkite-agent start --tags "queue=llamas,queue=alpacas"`

The agent configuration can have `tags=queue=llamas,queue=alpacas`. 

This causes the agent to listen on the `llamas` queue and the `alpacas` queue. It would be great to document this somewhere.

**Comment by harrietgrace** [comment]
That would be a great thing to add! We could add it to the [Queue doc](https://buildkite.com/docs/agent/v3/queues), and maybe a note in the [queue section](https://buildkite.com/docs/agent/v3/cli-start#the-queue-tag) of the agent `start` doc too. 

I'll leave this ticket open until that's added. Thanks @lox!

**Comment by NorseGaud** [comment]
Please :)
