### ISSUE TITLE
Add documentation for the default location of all buildkite files

### ISSUE THREAD

**Issue by ThomKoomen** [buildkite/docs#335]
In certain protected zones, where installing through package managers is both restricted and very slow to accept new packages, the buildkite agent may need to be "installed by hand".
This means unpacking the tarfile and placing its content in the appropriate locations.
However, I have not managed to find in the documentation what these appropriate locations are.
I understand I'm free to place these anywhere I want and pass in their paths through the configuration file (for which the location is documented), but I'd like to follow the way an "official" package manager installs its packages.

**Comment by harrietgrace** [comment]
Hey @ThomKoomen! Sorry you've had trouble finding that info ☹️

After having a look through the agent docs, the only file that has a defined location in the code is the config file itself: https://github.com/buildkite/agent/blob/90a2bc1b9767a48f647cfb8c5c62d416055dbf44/clicommand/agent_start.go#L104-L106

The other key files, like hooks and  are platform specific and are listed on each of the agent installer docs: https://buildkite.com/docs/agent/v3/ubuntu#file-locations

Does that help at all? I'm going to close this issue for the moment, but feel free to re-open it and let me know if you've got more questions, or if you'd like more info 😊

**Comment by ThomKoomen** [comment]
Hi @harrietgrace That helps immensely!
Though I'm not sure if I'm just blind or that it was sneakily added in the meantime...
Anyway thanks! 😄
