### ISSUE TITLE
Documentation for annotation limit

### ISSUE THREAD

**Issue by benschwarz** [buildkite/docs#337]
Hey! 

I wrote to support regarding annotations and learnt that while many annotations can be added to a build, only the first five are displayed. 

I spent a bunch of time reviewing my pipeline thinking that I'd done something wrong there — What do you think about a change to the docs to explain that only the first five will be displayed?

**Comment by harrietgrace** [comment]
Hey @benschwarz! Sounds like a great addition, I'll leave this issue open until I add it 😊
