### ISSUE TITLE
Some Links on Environment Variable page don't work

### ISSUE THREAD

**Issue by arthurk** [buildkite/docs#338]
On https://buildkite.com/docs/pipelines/environment-variables

>The bootstrap runs any local and global hooks that have been defined on the agent machine, and any *hooks* provided by *plugins*. Variables that are set in these hooks will be merged into the runtime environment, and will override any previous values that are set.

The "hooks" and "plugins" link lead to 404

**Comment by harrietgrace** [comment]
Ah no! Thanks for letting us know @arthurk 🙏🏻 I'll get a fix out for that today. I'll leave this issue open until it's merged 👍🏻

**Comment by harrietgrace** [comment]
That fix is live now 😊 Thanks again for reporting @arthurk! 🙌🏻
