### ISSUE TITLE
Docs should be searchable

### ISSUE THREAD

**Issue by vaughandroid** [buildkite/docs#35]
The docs are very useful, but would be even more useful if they were searchable.

Please make it happen!

**Comment by keithpitt** [comment]
Gah! YES! We've been wanting to do that for ages, but we first need to figure out _how_ to make them searchable :) We're focusing on re-doing our public pages at the moment, and as part of that, we'll figure something out!! 🔍

**Comment by joshprice** [comment]
Yes please, I just wanted this exact feature 🔍

**Comment by nchudleigh** [comment]
👍

**Comment by alexiamcdonald** [comment]
I have started this... kinda... not sure if I'll finish it but yeah here is something on a path to it.
https://github.com/alexiamcdonald/docs/tree/docs_searchable

**Comment by harrietgrace** [comment]
It's happened! Only four years later 😅 https://buildkite.com/changelog/91-search-in-buildkite-documentation
