### ISSUE TITLE
BUILDKITE_RETRY_COUNT is not documented

### ISSUE THREAD

**Issue by bjeanes** [buildkite/docs#351]
https://buildkite.com/docs/pipelines/environment-variables is missing `BUILDKITE_RETRY_COUNT` :)

https://buildkite-community.slack.com/archives/C02T53V9H/p1544579268085300?thread_ts=1544579008.084300&cid=C02T53V9H

**Comment by toolmantim** [comment]
I just moved it here to docs, so we can look at it for you @bjeanes. Thanks for the report!

**Comment by harrietgrace** [comment]
Thanks @bjeanes 🙏🏻 We've just released a big update to the [env vars doc](https://buildkite.com/docs/pipelines/environment-variables) which includes `BUILDKITE_RETRY_COUNT` 😊
