### ISSUE TITLE
launchctl on macos fails with "Could not find domain for"

### ISSUE THREAD

**Issue by szabolcsf** [buildkite/docs#353]
I need to install the buildkite-agent without homebrew. Want to run it as a service, so following the documentation: https://buildkite.com/docs/agent/v3/osx#starting-on-login

I do everything as documented, but launchctl can't load the plist file, it says `Could not find domain for `
Full output of my session:
```
$ curl -o ~/Library/LaunchAgents/com.buildkite.buildkite-agent.plist https://raw.githubusercontent.com/buildkite/agent/master/templates/launchd_local_with_gui.plist
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1414  100  1414    0     0   3495      0 --:--:-- --:--:-- --:--:--  3500
$ sed -i '' "s/your-build-user/$(whoami)/g" ~/Library/LaunchAgents/com.buildkite.buildkite-agent.plist
$ mkdir -p ~/.buildkite-agent/log && sudo chmod 775 ~/.buildkite-agent/log
$ launchctl load ~/Library/LaunchAgents/com.buildkite.buildkite-agent.plist
Could not find domain for 
```

Also tried with `https://raw.githubusercontent.com/buildkite/agent/master/templates/launchd.plist`, same issue. 
Please help. 
OS: macOS Mojave 10.14.1

**Comment by lox** [comment]
Hi @szabolcsf, that's a strange one! I've just downloaded the plist and customized it for paths that my agent is installed in:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  A launchd config for loading buildkite-agent on system boot on OS X
  systems, and runs in GUI mode (which allows Xcode UI testing but requires
  the user to login)
-->
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.buildkite.buildkite-agent</string>

    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/bin/buildkite-agent</string>
      <string>start</string>
      <!-- <string>--debug</string> -->
    </array>

    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>

    <key>RunAtLoad</key>
    <true/>

    <key>ProcessType</key>
    <string>Interactive</string>

    <key>ThrottleInterval</key>
    <integer>30</integer>

    <key>StandardOutPath</key>
    <string>/tmp/buildkite-agent.log</string>

    <key>StandardErrorPath</key>
    <string>/tmp/buildkite-agent.log</string>

    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin</string>

      <key>BUILDKITE_AGENT_CONFIG</key>
      <string>/usr/local/etc/buildkite-agent/buildkite-agent.cfg</string>
    </dict>
  </dict>
</plist>
```

I'm running 10.14.2, and my agent seems to start ok:

```bash
$ launchctl list | grep buildkite
31569	0	com.buildkite.buildkite-agent
```

Mind posting your config and checking all the directories exist and have correct permissions?

**Comment by szabolcsf** [comment]
I just upgraded to macOS 10.14.2, but the issue still persists. 
This is my plist file (`~/Library/LaunchAgents/com.buildkite.buildkite-agent-1.plist`):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  A launchd config for loading buildkite-agent on system boot on OS X
  systems, and runs without GUI (which starts on system boot, but doesn't allow Xcode UI testing)
-->
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.buildkite.buildkite-agent-1</string>

    <key>UserName</key>
    <string>user</string>

    <key>ProgramArguments</key>
    <array>
      <string>/Users/user/.buildkite-agent/bin/buildkite-agent</string>
      <string>start</string>
      <!-- <string>--debug</string> -->
    </array>

    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>

    <key>RunAtLoad</key>
    <true/>

    <key>OnDemand</key>
    <false/>

    <key>ProcessType</key>
    <string>Interactive</string>

    <key>SessionCreate</key>
    <true/>

    <key>ThrottleInterval</key>
    <integer>30</integer>

    <key>StandardOutPath</key>
    <string>/Users/user/.buildkite-agent/log/buildkite-agent-1.log</string>

    <key>StandardErrorPath</key>
    <string>/Users/user/.buildkite-agent/log/buildkite-agent-1.log</string>

    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin</string>

      <key>BUILDKITE_AGENT_CONFIG</key>
      <string>/Users/user/.buildkite-agent/buildkite-agent-1.cfg</string>
    </dict>
  </dict>
</plist>
```
The buildkite agent is in the /Users/user/.buildkite-agent directory (default when following the Linux/other installation method) and it's owned by user:staff:
```
macmini1:~ user$ id
uid=501(user) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh-disabled)
macmini1:~ user$ find /Users/user/.buildkite-agent ! -user user
macmini1:~ user$ find /Users/user/.buildkite-agent ! -group staff
macmini1:~ user$ launchctl list | grep build
macmini1:~ user$ 
```
I tried this on two different machines with macOS, but ran into the same problem. 

This is the agent configuration (`/Users/user/.buildkite-agent/buildkite-agent-1.cfg`):
```
# The token from your Buildkite "Agents" page
token="xxx"

# The name of the agent
name="macmini1-1"

# The priority of the agent (higher priorities are assigned work first)
# priority=1

# Meta-data for the agent (default is "queue=default")
# meta-data="key1=val2,key2=val2"

# Include the host's EC2 meta-data (instance-id, instance-type, and ami-id) as meta-data
# meta-data-ec2=true

# Include the host's EC2 tags as meta-data
# meta-data-ec2-tags=true

# Path to where the builds will run from
build-path="~/builds-1"

# Directory where the hook scripts are found
hooks-path="/etc/buildkite-agent/hooks"

# Do not run jobs within a pseudo terminal
# no-pty=true

# Don't automatically verify SSH fingerprints
# no-automatic-ssh-fingerprint-verification=true

# Don't allow this agent to run arbitrary console commands
# no-command-eval=true

# Enable debug mode
# debug=true

# Don't show colors in logging
# no-color=true

# Clean all the things!
git-clean-flags=-ffdxe_build

# add linux=true tag to target based on os
tags="osx=true"
```
the agent configuration has to be okay, since I can start the agent manually just fine, like this:
`macmini1:~ user$ cd .buildkite-agent && bin/buildkite-agent start --config buildkite-agent-1.cfg`

**Comment by szabolcsf** [comment]
I was able to solve this problem by putting my plist file to `/Library/LaunchAgents/com.buildkite.buildkite-agent-1.plist` and changing ownership of the file to root:wheel (permissions: 0600). This is the only way I could make `launchctl load` work.

**Comment by lox** [comment]
I'm going to re-open this as I'd like to improve our docs. I can reproduce this error when executed via SSH on a host where the GUI session is logged out.

**Comment by harrietgrace** [comment]
@lox how did you want to update the docs for this? Are we changing the instructions for Starting on Login? Or did you want to add a troubleshooting note that mentions that specific error?

**Comment by takn** [comment]
bump, i'm running into the same issue when building via packer...looks like launchctl doesn't like to load stuff when not logged in to the gui?

**Comment by harrietgrace** [comment]
Hey @takn, sorry you've run into this issue too. Have you been able to sort things out, or are you still having troubles? If you could shoot through an email to support@buildkite.com we can help you get things sorted 👍🏻

**Comment by trollfred** [comment]
For anyone who ends up here, launchd can't load user's services until it logs in via gui. Auto login feature can help in that case

**Comment by tizoc** [comment]
@trollfred thank you!

**Comment by johnfreed** [comment]
what is the "auto login feature" you refer to? exactly how does that work?

**Comment by tizoc** [comment]
@johnfreed see https://support.apple.com/en-ca/HT201476

**Comment by johnfreed** [comment]
@tizoc  thanks!

**Comment by hechunping** [comment]
> Just to confirm, when I log in via VNC, and re-run `launchctl load ~/Library/LaunchAgents/com.buildkite.buildkite-agent.plist` in the ssh session, it works fine.

Yes, this is the case with me, I am very fortunate to meet you.

**Comment by tcptps** [comment]
> For anyone who ends up here, launchd can't load user's services until it logs in via gui. Auto login feature can help in that case
@trollfred I am currently working on a small complete admins guide to launchd and therefore doing extensive research.
So far I can tell you that you need to add the following line to your plist file`                <key>LimitLoadToSessionType</key>
                <array>
                        <string>Aqua</string>
                        <string>LoginWindow</string>
                        <string>Background</string>
                        <string>StandardIO</string>
                </array>` and run the load and unload command with the -S Backgrond option. 
This is because by default (without <key>LimitLoadToSessionType</key>) launchd tries to load the agent into the Aqua context but this context doesnt exist when you are only logged in using ssh.

**Comment by tony-karandeev** [comment]
@tcptps I would be interested to read your guide. Where can I follow you?
