### ISSUE TITLE
Documentation: Unclear difference between job.started and job.activated

### ISSUE THREAD

**Issue by conorgil** [buildkite/docs#357]
The [job event documentation](https://buildkite.com/docs/apis/webhooks/job-events#events) does not explain the difference between `job.started` and `job.activated`.

References:
* [Slack convo](https://buildkite-community.slack.com/messages/C02T53V9H/)
* [Twitter thread](https://twitter.com/buildkite/status/1024288143808188417)

**Comment by harrietgrace** [comment]
Thanks @conorgil, better explanations for those events would be super. I'll leave this issue open until they get added 👍🏻
