### ISSUE TITLE
Team filtering for cc-menu integration

### ISSUE THREAD

**Issue by jleskovar-tyro** [buildkite/docs#359]
Hey guys,

Any possibility of adding team filtering for the CC-menu integration? Similar to how you can currently filter on branch, possibly something like:

`https://cc.buildkite.com/org.xml?branch=master&team=someTeamName&access_token=...`

**Comment by harrietgrace** [comment]
Hey @jleskovar-tyro, mind dropping us a feature request in https://forum.buildkite.community/c/feature-requests? We use this docs repo specifically for things that need fixing in our documentation, whereas the forum keeps track of feature requests! 😊
