### ISSUE TITLE
why can my Docker host can fill up with a lot of unused images?

### ISSUE THREAD

**Issue by nhooyr** [buildkite/docs#366]
> Even though the buildkite agent cleans up the images after each run, inevitably over time your Docker host can fill up with a lot of unused images.

if it cleans up images after each run, how would my host fill up?

**Comment by toolmantim** [comment]
If your commands/scripts pull or run images, outside of using the plugins, then unfortunately this can happen! Let me know if that answers your question, or if you'd like more details, or you think the doc should be improved to make this clearer.

**Comment by nhooyr** [comment]
The agent doesn't seem to clean up images after every run, at least not in the buildkite docker build plugin.

Also what is https://github.com/buildkite/agent/blob/master/packaging/linux/root/usr/share/buildkite-agent/docker-cleanup.sh for ?

And the docs should only recommend a single tool for cleaning up images. Or explain when `docker system prune` would be preferable to `docker-gc`.

**Comment by toolmantim** [comment]
> The agent doesn't seem to clean up images after every run, at least not in the buildkite docker build plugin.

No, it doesn't, we didn't include any on purpose. The Docker Compose plugin does clean up the project-based images (but not standard tags, such as `alpine:latest`. Are you finding it a problem?

`docker-cleanup.sh` is an old file I believe — I've just opened https://github.com/buildkite/agent/pull/914 to remove it.

I believe  `docker system prune` should be the preferred default, but the idea is that it's good to know that there are alternatives such as `docker-gc`.

**Comment by nhooyr** [comment]
> No, it doesn't, we didn't include any on purpose. The Docker Compose plugin does clean up the project-based images (but not standard tags, such as `alpine:latest`. Are you finding it a problem?

Nah, just trying to understand the precise behaviour here. The docs should be modified to reflect that the only docker compose plugin does cleanup.

> I believe `docker system prune` should be the preferred default, but the idea is that it's good to know that there are alternatives such as `docker-gc`.

It adds more choice for a user which is confusing when you can't really tell the difference. See https://github.com/spotify/docker-gc/issues/199

**Comment by toolmantim** [comment]
There was a time where `docker system prune` was very new, and so we had to give alternatives for newer and older Dockers… and prune didn’t have all the options it does now. But having looked at those (and comparing them more closely) we can probably just remove the `docker-gc` link now! 👌🏼

**Comment by toolmantim** [comment]
> The docs should be modified to reflect that the only docker compose plugin does cleanup.

Which doc are you referring to?

**Comment by nhooyr** [comment]
@toolmantim https://buildkite.com/docs/tutorials/docker-containerized-builds#adding-a-cleanup-task

**Comment by toolmantim** [comment]
Thanks @nhooyr! I've just opened a PR to clarify things.
