### ISSUE TITLE
Why do the examples use env variables to set agent token if its not recommended?

### ISSUE THREAD

**Issue by nhooyr** [buildkite/docs#367]
https://buildkite.com/docs/agent/v3/docker#configuring-the-agent

> Most agent configuration settings can be set with environment variables. Setting sensitive data, (such as the agent token) via environment variables or command line arguments is not recommended as they are exposed in commands such as docker inspect.

Right above it there is an example of running the agent as so

```
docker run -e BUILDKITE_AGENT_TOKEN="INSERT-YOUR-AGENT-TOKEN-HERE" buildkite/agent
```

which is entirely contradictory.

**Comment by toolmantim** [comment]
That’s a great point @nhooyr 🤔 We should check if `docker run buildkite/agent start --token xxx` is the better option here.

**Comment by nhooyr** [comment]
Command line arguments are also not recommended for the same reason.

**Comment by toolmantim** [comment]
You're right! That's no better either.

I think the first `docker run buildkite/agent` examples were intended to show how easy it is to start an agent (vs having to echo the token into a config file and host mount it into the container), and is targeting a first time Buildkite user wanting to run a test agent on a dev machine. But then later recommendations are addressing "production" setups. Although that might have been our initial intention, it's totally unclear, inconsistent, and can be improved. Thanks for bringing it up!

We've got some ideas on how to improve the security of things, and not just in documentation.

Firstly, we could prompt and accept it via STDIN, then it's not in your bash history, and nowhere outside of the agent process:

```bash
$ docker run -it --rm buildkite/agent start
Agent token required. You can find yours at https://buildkite.com/organizations/-/agents
Enter your agent token: ••••••••••••••••••
```

If you use Swarm/ECS/k8s they all have their own secrets management features, which usually work via a file or an env, but this could work for a local dev w/ TTY experience.

Another improvement we could make, is that although we allow you to create multiple agent tokens via the GraphQL API, the web UI doesn't have any buttons to easily create them. Making it easier for people to create new dev/throwaway agent tokens (perhaps that expire after x days) would make the default "just get started" experience more secure.

If you've got ideas based on your experience, we'd love to hear them! We'll try to update this documentation in the meantime anyhow, regardless of those above ideas.

**Comment by nhooyr** [comment]
stdin sounds solid to me.

**Comment by nhooyr** [comment]
also you guys should update the k8s example to not use an environment variable either.

**Comment by nhooyr** [comment]
Actually, what makes env variables insecure? Anyone who can run `docker inspect` on the host can very likely just exec into the container and steal the token via the config file anyway (the only other option afaik).

**Comment by toolmantim** [comment]
Yep, the stdin suggestion wasn’t about trying to hide it from people having root host machine access. It’s more just trying to think of the common use case patterns, and making them more secure and less error prone. For example, it’s common you might start trying out Buildkite on your dev machine and use the same agent in your production cluster later on. It’s be nice if if this wasn’t the same token, and/or if the token wasn’t sitting around in your `docker ps` and bash history on your machine.

Environment variables on a production cluster might not be a problem at all.

**Comment by nhooyr** [comment]
> It’s be nice if if this wasn’t the same token, and/or if the token wasn’t sitting around in your `docker ps` and bash history on your machine.

If someone has access to my machine, all bets are off anyway. They'd get my SSH keys easily and a whole host of other stuff. I think the convenience of env variables is worth the minor trade off in security. Passing the token via stdin is also really clunky if you want to restart the agent because you've modified a hook/made some other change, you need to enter the token again and again.

I think the docs should be changed to elaborate on why env variables can be insecure but not recommend against them. And then recommend using a different token for when your testing locally versus once you've put the agent in production.

**Comment by toolmantim** [comment]
> If someone has access to my machine, all bets are off anyway. They'd get my SSH keys easily and a whole host of other stuff.

Yep, for your case I think you’re right. But in Buildkite, agent tokens are attached to an organization and not to an individual. In larger teams, where people might have left the org (and you’ve revoked their SSH access etc), you don’t want organization-level credentials floating around.

I think for your case, it sounds like a docs update might suffice.

But for larger orgs, I can still see a big benefit to both accepting the token via stdin, and a better default UI/UX for token setup and testing.

**Comment by nhooyr** [comment]
Multiple agent tokens should then be allowed to be created and named, sort of like API tokens. Then whoever is in the organization can revoke or hand out new tokens as necessary.

For testing, maybe if you run the Buildkite Agent without a token and it detects a terminal, it prompts for your login information and organization to grab a new token for the organization. Maybe buildkite could support an expiry date on the API token so such tokens would only be for testing and expire after say 48 hours.

**Comment by nhooyr** [comment]
Also, if the agent token is compromised is there a way to regenerate it at the moment?

**Comment by toolmantim** [comment]
I believe #401 and #402 should cover both the things you've raised, and your questions about agent management. Feel free to email support@buildkite.com if you need, and thanks for the feedback @nhooyr!
