### ISSUE TITLE
inconsistency in docs

### ISSUE THREAD

**Issue by nhooyr** [buildkite/docs#368]
https://buildkite.com/docs/pipelines/defining-steps#further-documentation

> You can also create pipelines using the buildkite-agent command line tool. See the buildkite-agent pipeline documentation for a full list of the available parameters.

But you cannot create a pipeline with the listed tool? You can only upload new steps or replace steps. And this has already been show on the page above that section.

See https://buildkite.com/docs/agent/v3/cli-pipeline

> The Buildkite Agent’s pipeline command allows you to add and replace build steps in the running build.

**Comment by harrietgrace** [comment]
Hey @nhooyr, that section could definitely be clearer! I think that particular bit was making the assumption that the reader is already using a pipeline.yml file to upload their steps, so the terms 'create' and 'upload' got accidentally conflated. 

I've updated the section to make it clearer that it's the 'upload' function that is available from the command line.
