### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nhooyr** [buildkite/docs#369]
https://buildkite.com/docs/agent/v3/hooks#available-hooks

Re environment hook:

> Runs before all other commands. Useful for exposing secret keys and security whitelisting.

I believe it was meant that it runs before all other hooks.

**Comment by harrietgrace** [comment]
Good catch! Thanks for letting us know 👌🏻

**Comment by nhooyr** [comment]
I think I was wrong actually. It also runs not just before all other hooks but also for example, if you don't use a checkout hook, it will run before whatever Buildkite uses as the default git checkout command. I guess this could be clarified.
