### ISSUE TITLE
document usage of `---` to create log groups

### ISSUE THREAD

**Issue by nhooyr** [buildkite/docs#372]
Don't see this behaviour documented anywhere. Using `---` in the output of a command starts a log group you can fold on the frontend.

**Comment by harryi3t** [comment]
@lox Does this not work if we put this in a script that is executed from the main command?
```js
# main pipeline

- label: 'some step'
- command: 'some-script.bat'
```

```bat
:: some-script.bat

echo "--- Group 1"
npm i
```

**Comment by lox** [comment]
It should work! 🤔 Wanna drop us an email at support@buildkite.com @harryi3t
