### ISSUE TITLE
Plugin directory needs documenting

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#388]
The only thing holding back https://buildkite.com/plugins is having some documentation on it.

Things I want to cover, between the directory and the docs:

* If you end up at the plugin docs page, we should make you aware of the plugin directory.
* People might want to know "What is a plugin? Tell me more" when they're looking at the plugin directory page. (We link to the plugins page at the top of the plugin directory)
* People might want to know "How do I submit a plugin to the directory?" — when they're looking at the plugin directory page (from the link/call to action on the bottom), or from the documentation on how to create a plugin.
* There are plugins in GitHub that don't appear on the directory, because they don't meet the requirements. People will wonder why theirs isn't showing. We should have some bullet points in the docs for how the directory figures out what is included.

**Comment by harrietgrace** [comment]
Can plugins hosted elsewhere be included? Are there plugins that live elsewhere? I've not checked Bitbucket or anything.

**Comment by toolmantim** [comment]
Yep, we should definitely mention all the places plugins can be hosted. They can be in a private git repository, public repositories (like BitBucket), in the repository itself, or locally on a the agent's filesystem.

**Comment by harrietgrace** [comment]
New plugins docs section is live! https://buildkite.com/docs/plugins 🎉
