### ISSUE TITLE
elaborate on force clean checkouts

### ISSUE THREAD

**Issue by nhooyr** [buildkite/docs#397]
https://buildkite.com/docs/agent/v3/securing#forcing-clean-checkouts

> By default Buildkite will reuse (after cleaning) a previous checkout. This may not be safe if building commits from untrusted sources (e.g. 3rd party pull requests). To force a clean checkout every time, set BUILDKITE_CLEAN_CHECKOUT=true in the environment.

Its not clear to me why building a commit from an untrusted source would be insecure when reusing a previous checkout.

**Comment by toolmantim** [comment]
Being able to place code into that directory, which might carefully take into account `git clean` rules, might mean that a file from a previous build might be included in a compiled binary for example. It's hard to describe all the attack vectors, but they're all part of the "cache poisoning" variety.

The ultimately "clean build" is an entire VM for each job, with no shared checkout cache. But we've included this instruction for people wanting to run third-party PRs from the other direction… starting with the standard agent setup.

I hope that clarifies things!
