### ISSUE TITLE
Docs on enterprise features

### ISSUE THREAD

**Issue by jamiekyle-eb** [buildkite/docs#399]
It would be great to have documentation that better specifies these enterprise features:

- Audit Logging: Seeing what data is available in these logs
- Access Control & Teams

Since these features can only be seen via reaching out to sales@buildkite.com and having your account turned into an enterprise account, it would be great to at the very least see screenshots of the features publicly accessible.

**Comment by harrietgrace** [comment]
Hey @jamiekyle-eb, thanks for letting us know! I brought this up with the team and we've been chatting internally about how to best present this kind of info, so adding it to the docs is still in the works at the moment 😊I'll leave this issue open until it's added 👍🏻

**Comment by plaindocs** [comment]
Closing this as we have docs on teams and audit logging now.
