### ISSUE TITLE
Agent token documentation

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#401]
As mentioned in #367, it might be a good idea if we had some documentation around agent token management? Especially the fact that you can create and revoke agent tokens using GraphQL, which a lot of people don't know about. 

We could then link to this page from all the installer and configuration documentation? And a changelog about this doc update might be a good way to let everyone know about it too?

Here’s the GraphQL to get us started…

## List all active agent tokens

```graphql
query {
  organization(slug: "my-org") {
    agentTokens(revoked: false) {
      edges {
        node {
          createdAt
          description
          token
        }
      }
    }
  }
}
```

## Revoke an agent token

```graphql
mutation {
  agentTokenRevoke(input: {
    id: "<token-id>",
    reason: "A reason"
  }) {
    agentToken {
      description
      revokedAt
      revokedReason
    }
  }
}
```

## Create an agent token

```graphql
mutation {
  agentTokenCreate(input: {
    organizationID: "<organization-id>",
    description: "A description"
  }) {
    agentTokenEdge {
      node {
        id
        token
      }
    }
  }
}
```

**Comment by harrietgrace** [comment]
Thanks for the code samples! 🙌🏻I think those would be great in a new page under the GraphQL API sub-section. 

Do you think there's enough to say about managing agent tokens (other than the code examples) that we could have a whole new page under the Agent heading? What kinds of info had you imagined we would include? Some ideas I had:

- It could be called 'token management' or something equally broad
- Info about where to store your tokens, locally vs parameter stores
- Something about docker
- What the token allows you to access/do, so that people can understand the risks of insecure storage
- Link to the graphQL docs with those code samples

**Comment by toolmantim** [comment]
Yeah, I think it's definitely worth a page! And a changelog 🙌🏼

We link to the docs from the Agents page, and it'd be nice for admins and first time people to get a firm grasp of what tokens are exactly, and the security implications of them. They're also one of the most sensitive pieces of data in your Buildkite organization.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/153/53058953-4596cf80-3509-11e9-8f54-26d59dfda412.png">

Also the UI for agent tokens is seriously lacking at the moment (at the moment, the GraphQL queries are the "UI"), and some people don't know they can (and should have) multiple agent tokens.

If we add a page in the documentation, we can update the copy in the Agents tab to say something like `See the [agent tokens documentation](/docs/agent/v3/tokens) for how to create and revoke tokens`. When we update the UI, we can update the docs, and make less of a big deal about the GraphQL queries.

I was thinking the nav item could be called "Tokens" and the page title "Agent Tokens"? The only problem is that hardly any of this doc is agent version specific? Perhaps not a problem?

Here's a first draft, which is probably close(ish) to a v1?

    # Agent Tokens

    The Buildkite Agent requires an agent token to connect to Buildkite and register for work. If you are an admin of your Buildkite organization, you can view the tokens on your [Agents page](https://buildkite.com/organizations/-/agents).

    <%= toc %>

    ## The default token

    When you create a new organization in Buildkite, a default agent token is created. This token can be used for testing and development, but it's recommended to [create new, specific tokens](#creating-tokens) for each new environment.

    ## Using and storing tokens

    The token is used by the Buildkite Agent’s [start](/docs/agent/v3/cli-start#starting-an-agent) command, and can be provided on the command line, set in the [configuration file](/docs/agent/v3/configuration), or provided via the [environment variable](/docs/pipelines/environment-variables) `BUILDKITE_AGENT_TOKEN`. 

    It's recommended you use your platform’s secret storage (such as the [AWS Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) to allow for easier rollover and management of your agent tokens.

    ## Creating tokens

    New tokens can be created using the [GraphQL API](/docs/apis/graphql-api) with the `agentTokenCreate` mutation, for example:

    ```graphql
    mutation {
      agentTokenCreate(input: {
        organizationID: "<organization-id>",
        description: "A description"
      }) {
        agentTokenEdge {
          node {
            id
            token
          }
        }
      }
    }
    ```

    The token description should clearly identify the environment the token is intended to be used for, and is shown on your [Agents page](https://buildkite.com/organizations/-/agents).

    ## Revoking tokens

    Tokens can be revoked using the [GraphQL API](/docs/apis/graphql-api) with the `agentTokenRevoke ` mutation, for example:

    ```graphql
    mutation {
      agentTokenRevoke(input: {
        id: "<token-id>",
        reason: "A reason"
      }) {
        agentToken {
          description
          revokedAt
          revokedReason
        }
      }
    }
    ```

    Once a token is revoked, no new agents will be able to start with that token. Revoking a token does not affect any connected agents.

    ## Scope of access

    Agent tokens are specific to each Buildkite organization, and can be used to register an agent with any [queue](/docs/agent/v3/queues). Agent tokens can not be shared between organizations.

    ## Session tokens

    During registration, the agent exchanges the agent token for a session token. The session token is exposed to the job as the [environment variable](/docs/pipelines/environment-variables) `BUILDKITE_AGENT_ACCESS_TOKEN`, and is used by the [annotate](/docs/agent/v3/cli-annotate), [artifact](/docs/agent/v3/cli-artifact), [meta-data](/docs/agent/v3/cli-meta-data) and [pipeline](/docs/agent/v3/cli-pipeline) commands. Session tokens are scoped to a specific agent, and are valid for the duration the agent is connected.
