### ISSUE TITLE
Layout problems on the ADFS SSO guide

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#403]
I noticed that https://buildkite.com/docs/integrations/sso/adfs has some odd layout of the sub-steps — perhaps something went wrong in the markup matrix?

**Comment by harrietgrace** [comment]
It looks like sublists like 1.1 blah 1.2 blah etc. don't work in markdown 😒I'll swap it out for something else. Thanks for letting me know! 👍🏻
