### ISSUE TITLE
GitHub integrations page

### ISSUE THREAD

**Issue by sj26** [buildkite/docs#409]
We list GitHub Enterprise in our integrations page. It'd be great to list GitHub (github.com) as well to make it clear that we have integration, and briefly mention what is supported and how to link GitHub and Buildkite accounts. Maybe even a brief note about noreply email handling.

**Comment by harrietgrace** [comment]
Great idea! I'll leave this open until it's added 😊Thanks @sj26!

**Comment by plaindocs** [comment]
Hey @sj26 do you have a link somewhere to what you mean by noreply email handling?

**Comment by sj26** [comment]
@plaindocs when you connect your GitHub account on https://buildkite.com/user/connected-apps we also automatically add you `[username]@users.noreply.github.com` email address to your buildkite user account. If you're using the GitHub setting which hides your email, it will replace it with this noreply email, so knowing about it helps Buildkite link builds created by commits pushed to github by your email to your Buildkite user account. :-)

**Comment by plaindocs** [comment]
Gotcha.

Does it handle the username@ OR username+IDnumber@ variant? 

And at first glance, it is isn't findable in your Buildkite settings, is that correct or am I looking in the wrong place?

**Comment by sj26** [comment]
So my advice wasn't technically correct — we add whatever email github gives us to your account. For me, this is my actual email address. For others, it'll be the latest flavour of github's noreply email. So disconnecting and reconnecting might sometimes give a newer or updated email. This is an implementation detail so isn't spelled out in any settings page, although you can see the effects (if any) in the [user email settings page](https://buildkite.com/user/emails).

**Comment by plaindocs** [comment]
Thanks! Can you check if 15fd91a  is a reasonable distillation of what you've just said?

**Comment by sj26** [comment]
@plaindocs sounds right to me! :+1:
