### ISSUE TITLE
Create a pipeline

### ISSUE THREAD

**Issue by sj26** [buildkite/docs#410]
We have docs on [the pipelines page](https://buildkite.com/docs/pipelines), and [defining steps](https://buildkite.com/docs/pipelines/defining-steps) within an existing pipeline, but we're missing a step in the middle about creating a new pipeline. It's pretty easy to figure out once you're in the Buildkite dashboard, but folks evaluating us externally with documentation don't have a nice reference for what to expect.

**Comment by harrietgrace** [comment]
Huh, what an oversight 😅 Thanks for pointing it out @sj26! There's not even anything in the getting started guide about creating a pipeline from scratch, there's only the 'add a pipeline' button 😬

Do you think that this section should be in it's own doc, or would it fit better in a re-written/more in depth getting started guide?

**Comment by sj26** [comment]
I wasn't super sure to be honest, which is why I didn't have a crack at it myself. 😅 It kinda feels relevant as a "step 0" in https://buildkite.com/docs/pipelines/defining-steps#getting-started, but also feels relevant as a segue from "What is a Pipeline?" in https://buildkite.com/docs/pipelines#what-is-a-pipeline. Maybe on the _Defining Steps_ page makes more sense.

**Comment by sj26** [comment]
I think it's also tricky when trying to tease apart the two definitions of "pipeline" — "a group of builds with a name and a build template" versus "a sequence of steps" which can be on the build template or a particular build.

**Comment by harrietgrace** [comment]
I think having it at the start of Defining Steps sounds like a good place to try! We could add a link to the new section to the "What is a pipeline" section too, so that it's more obvious. 

I'll have a go at adding it to Defining Steps and we can see how it feels!
