### ISSUE TITLE
Hyperlinks in job output undocumented

### ISSUE THREAD

**Issue by ticky** [buildkite/docs#412]
We [support hyperlinks in job output](https://github.com/buildkite/terminal-to-html/blob/bc7274cbce9fb5c752c32fdb4ea267cb4260417f/link.sh) using our underlying `terminal-to-html` renderer, however, this code is not documented and, presumably, left as an exercise for the reader to know we’re imitating iTerm 2 and co!

It’d be good to add this, perhaps alongside the existing [images in job output](https://buildkite.com/docs/pipelines/images-in-log-output) doc.

**Comment by harrietgrace** [comment]
Rad, thanks for making an issue about it @ticky! 🙌🏻I'll leave this open until it's added.

**Comment by ticky** [comment]
@harrietgrace I’d be happy to draft this up, do you think it should be its own page, or should the existing “Images in job output” be renamed, maybe to “Links and images in job output” (w/ redirect)?

**Comment by toolmantim** [comment]
I reckon the latter?

**Comment by ticky** [comment]
I have realised that our codes aren’t the same as iTerm’s - ours are in fact completely incompatible with iTerm’s! Opened this issue around that: buildkite/terminal-to-html#58
