### ISSUE TITLE
Running agent in docker commands are incorrect

### ISSUE THREAD

**Issue by phantomwhale** [buildkite/docs#420]
https://buildkite.com/docs/agent/v3/docker

advises running `docker run -d -t buildkite-agent buildkite/agent:3 start --token "<insert-token>"`

But this throws an error:

```
Unable to find image 'buildkite-agent:latest' locally
docker: Error response from daemon: pull access denied for buildkite-agent, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

Removing the `buildkite-agent` argument seems to correctly download the buildkite/agent:3 image - I'm not sure what this argument was being used for?

**Comment by lox** [comment]
Sorry about that! I'm not sure what the `buildkite-agent` was in there for either! Removing it is correct and we'll do that.

**Comment by lox** [comment]
I suspect it was meant to have `--name` before it.
