### ISSUE TITLE
Bitbucket docs don’t mention setting Bitbucket server URL

### ISSUE THREAD

**Issue by ticky** [buildkite/docs#423]
For us to recognise a Bitbucket server instance, we need the URL set in https://buildkite.com/organizations/-/settings. Currently, our Bitbucket docs don’t mention this - I think we used to have a separate guide, but it was deemed unnecessary perhaps without considering this extra step!

**Comment by harrietgrace** [comment]
Definitely keen to have some Bitbucket Server docs! We had a couple of tickets this week about getting it set up. I'll leave this open until I get those added 👍🏻

**Comment by plaindocs** [comment]
Bitbucket Server is being deprecated, so I think we can  close this?

**Comment by StarfallProjects** [comment]
Fixed by https://github.com/buildkite/docs/pull/1005
