### ISSUE TITLE
Document include_retried_jobs

### ISSUE THREAD

**Issue by sj26** [buildkite/docs#425]
The REST API builds endpoints have an optional `include_retried_jobs=true` parameter which can include retried jobs which are excluded by default. We should add it to the docs.

**Comment by harrietgrace** [comment]
Ah cool, thanks @sj26! 👌🏻I'll leave this open until it's added.

**Comment by harrietgrace** [comment]
It looks like there's also the option to `exclude_project` or `exclude_jobs`, are those just used internally, or should they get added to the docs too?

**Comment by toolmantim** [comment]
`include_retried_jobs` is the only one that's supported in the API, those other two are for other internal bits of code that want to exclude projects and jobs
