### ISSUE TITLE
Remove Domain Name from SSO guides

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#447]
We no longer need the domain name from people to set up SSO for them, so we can remove that requested information from the SSO guides, for example:

> Domain name - The domain you use with Google Cloud Identity for which you want to enable SSO. This must match one of the emails you have verified with your Buildkite account.

**Comment by harrietgrace** [comment]
Sweet, thanks @toolmantim! I'll leave this open until I've removed them 👍🏻

**Comment by harrietgrace** [comment]
Looks like this was completed in the latest round of updates to the SSO docs, when they were changed to be self-serve.
