### ISSUE TITLE
Document how to load balance between agents using the agent priority

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#454]
As mentioned in https://github.com/buildkite/feedback/issues/422 a big use case for the `priority` agent configuration is to load balance across a number of agent machines.

We might want to add a new section to https://buildkite.com/docs/agent/v3/prioritization that documents this usage pattern.

**Comment by harrietgrace** [comment]
Sweet, thanks Tim! I'll leave this open until it's added.
