### ISSUE TITLE
buildkite-agent.service failed to start

### ISSUE THREAD

**Issue by nguyenvudao** [buildkite/docs#455]
Hi everyone, I'm try to start the agent with 

> sudo systemctl enable buildkite-agent && sudo systemctl start buildkite-agent

But the logs show me this picture:
![ODa4U59](https://user-images.githubusercontent.com/22849827/56081163-6a862f80-5e34-11e9-812b-d90e4ef86ee8.png)

Can anyone show me how to fix it? I've read docs but can find in nowhere

**Comment by harrietgrace** [comment]
Hey @nguyenvudao, sorry to see you've run into issues getting the agent going. If you send us an email to support@buildkite.com we can help you debug what's going on.
