### ISSUE TITLE
Set permissions progrmatically on teams for a pipeline

### ISSUE THREAD

**Issue by amazingankur** [buildkite/docs#456]
Hello,

I am facing problem in setting permissions programatically to the teams. 
I am able to create a pipeline programatically and assign teams to it but by default it give full access to all the added teams. Is there a parameter which I can pass for team permissions. I tried finding one in API documentation but couldn't.
Thanks

**Comment by harrietgrace** [comment]
Hey @amazingankur! Sorry you're running into trouble with the teams permissions, and sorry for the delayed response to your issue. 

There is a permissions parameter, but only if you're using the GraphQL API. You can pass an 'accessLevel' param along with your team id when you're creating a pipeline with GraphQL. Unfortunately our REST API doesn't have the same level of team support. 

You can find that param in the GraphQL docs sidebar of the [Buildkite GraphQL Explorer](https://graphql.buildkite.com/explorer) under: mutations > PipelineCreate > PipelineCreateInput > PipelineTeamAssignmentInput.

![image](https://user-images.githubusercontent.com/2074469/57508678-869ec300-7345-11e9-89f8-3be4f3982e22.png)
