### ISSUE TITLE
Documentation for configuring GitHub pipeline rules/settings

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docs#472]
While looking at adding builds on forks, @plasticine and I were wondering "Do we have to update the docs if we add a new setting to the "GitHub" section in the pipeline settings. It doesn't look like there's any docs on it.

There's probably a good case for some docs, only because there's some patterns we recommend for common things that are a bit quirky with the way things currently work.

For example, if you only want to run a pipeline on pull requests, you have to set the "Brand filter pattern" on the pipeline to some branch name that will never occur (e.g. "this-branch-will-never-occur"). Pull request builds ignore the branch filter patterns, and all pushes to other branches (e.g. master/stable/beta/etc) will be ignored.

Perhaps it's worth adding a section that explains how to set up various common scenarios/patterns using our settings page as it is today? And down the track we can revisit the way the settings work, and integrate some of the use cases that docs had to help people with.

**Comment by plaindocs** [comment]
@toolmantim @plasticine @harrietgrace do you know of any more patterns? Or is the PR only thing enough for now.
