### ISSUE TITLE
Agent version selector doesn't work

### ISSUE THREAD

**Issue by evanderkoogh** [buildkite/docs#473]
It looks like there is an issue with the version selector on the agent documentation.

It looks like the content for the  javascript tag for the selector in https://github.com/buildkite/docs/blob/4d6daee7cb0b7cebd78591d22660d014677519a1/app/views/layouts/application.html.erb#L100-L109 is turned into CDATA

<img width="681" alt="Screen Shot 2019-05-16 at 10 54 39 pm" src="https://user-images.githubusercontent.com/890386/57855668-8b281780-782e-11e9-97c0-546520b0e8b4.png">

**Comment by harrietgrace** [comment]
Oh dear! Thanks for letting us know @evanderkoogh 🙏🏻 I'll leave this open until we push a fix.

**Comment by toolmantim** [comment]
Looks like it's also broken on the live docs site! (and not just the new standalone app). We should add a test or two.

**Comment by toolmantim** [comment]
Thanks for spotting that @evanderkoogh! Turns out the CSP setup wasn't correct, and the layout we're using in production isn't quite the one you found in this repository (the source of the error was slightly different). That's been fixed in #476 if you wanted to take another look!

**Comment by evanderkoogh** [comment]
If only you used this tool I heard about the other day that has preview links on every PR 😂

But good to know that is how at least Firefox treats it’s bad CSP inline script. Bit of a weird way. Glad you caught it!

**Comment by toolmantim** [comment]
I would totally pay for that tool!
