### ISSUE TITLE
Document provider_settings for the pipelines API

### ISSUE THREAD

**Issue by pecigonzalo** [buildkite/docs#481]
Currently the section for `provider_settings` is undocumented, and its hard to find what parameters are accepted or how to enter them. I did some checking on https://github.com/buildkite/go-buildkite/blob/master/buildkite/providers.go#L48 and it seems not all settings are "documented" or codified there.

eg. `separate_pull_request_statuses`

We are currently building a quick tool to bootstrap pipelines form a yaml/json definition till we/someone works on https://github.com/buildkite/cli/issues/48

**Note**
This probably should be another issue, but I also notice the API accepts YAML as well: https://github.com/buildkite/python-docker-example/blob/master/.buildkite/template.yml maybe it would be good to add that.

**Comment by harrietgrace** [comment]
Hey @pecigonzalo, sorry it has taken me so long to get back to you on this one 😣 We definitely need a full list of the available `provider_settings`, thanks for pointing out that gap 🙏🏻

I've started putting together some new tables for this on the pipeline API page - the basic list in this draft PR for now, if you wanted a sneak peek: https://github.com/buildkite/docs/pull/528 

Was there a specific property that you were looking for the syntax for, or was it just a general need for more comprehensive docs on the topic? 😄

**Comment by pecigonzalo** [comment]
We were trying to create a `.yml` or `.json` and programmatically create pipelines, as most of our pipelines follow the same initial parameters and to simplify the developer's workflow.
EG:
```
#!/bin/bash

set -euo pipefail

# Populate pipeline data
BUILD="$(envsubst <buildkite-bootstrap/pipeline.build.json)"
DEPLOY="$(envsubst <buildkite-bootstrap/pipeline.deploy.json)"

curl -X POST \
    --silent -f --show-error --output /dev/null \
    "https://api.buildkite.com/v2/organizations/$ORG/pipelines" \
    -H "Content-type: text/x-yaml" \
    -H "Authorization: Bearer $BUILDKITE_TOKEN" \
    -d "$BUILD"

curl -X POST \
    --silent -f --show-error --output /dev/null \
    "https://api.buildkite.com/v2/organizations/$ORG/pipelines" \
    -H "Content-type: text/x-yaml" \
    -H "Authorization: Bearer $BUILDKITE_TOKEN" \
    -d "$DEPLOY"
```

And configs as:
```
{
  "name": "${NAME}",
  "repository": "git@github.com:${ORG}/${NAME}.git",
  "branch_configuration": "master",
  "skip_queued_branch_builds": true,
  "skip_queued_branch_builds_filter": "!master",
  "cancel_running_branch_builds": true,
  "cancel_running_branch_builds_filter": "!master",
  "provider_settings": {
    "build_pull_requests": true,
    "separate_pull_request_statuses": false,
    "PublishCommitStatus": true,
    "SkipPullRequestBuildsForExistingCommits": true
  },
  "steps": [{
    "type": "script",
    "command": "buildkite-agent pipeline upload",
    "label": ":pipeline:"
  }]
}
```

**Comment by pecigonzalo** [comment]
<3 @harrietgrace
