### ISSUE TITLE
Docs don't make it clear that we support Github

### ISSUE THREAD

**Issue by lox** [buildkite/docs#493]
Looking at https://buildkite.com/docs/integrations it's not immediately clear that we support GitHub (cloud?) as well as GitHub Enterprise. Let's clearly list it so that folks can be certain we support it.

**Comment by sj26** [comment]
Related — https://github.com/buildkite/docs/issues/472

**Comment by sj26** [comment]
Maybe a duplicate of https://github.com/buildkite/docs/issues/409

**Comment by harrietgrace** [comment]
Closing as a duplicate of #409 🙏🏻
