### ISSUE TITLE
Documentation for branch negation is unclear

### ISSUE THREAD

**Issue by pfaucon** [buildkite/docs#514]
https://buildkite.com/docs/pipelines/branch-configuration#branch-pattern-examples 

states:
`
!production will match any branch that's not production (this value should be quoted if defined in a YAML file and uploaded via buildkite-agent pipeline upload)
`

it is not clear whether `this value should be quoted` means that it should look like
` branches: "beta !production"`
or
` branches: "beta '!production''`

Typically I would assume the first, but given that every example has been quoted, and that a special emphasis was put on the statement maybe the second is correct?  In either case it might be good having at least one example with the branch negation.

**Comment by harrietgrace** [comment]
Hey @pfaucon, that is indeed confusing! I've asked the team about it and will get back to you with an answer and a clearer example 👍🏻

**Comment by harrietgrace** [comment]
Hi again @pfaucon, it looks like that parenthetical about quotes is a bit misleading. I think originally it was intended to underscore the importance of wrapping the entire value in quotes, but it sounds like it's saying just to wrap the negative values in quotes! I'll remove it 👍🏻

So the correct amount of quotes would be just the one set, as in `branches: "beta !production"`. Let me know if you'd like any further info or have any other questions 😊
