### ISSUE TITLE
Soft-fail blocks wait step

### ISSUE THREAD

**Issue by bar-myob** [buildkite/docs#525]
We added a soft-fail attribute before a wait step and it blocks,
this could be solved by adding a 'continue_on_soft_failure' to wait step.

**Comment by harrietgrace** [comment]
Hey @bar-myob, sorry that you've been running into issues with the soft-fail and wait steps! 😣 

I haven't been able to replicate a soft-fail blocking a wait step - would you be able to send an email through to support@buildkite.com with some more information about the specific circumstances and the build you're seeing the issues with? We can have a look at what's going on and help sort things out 👍🏻
