### ISSUE TITLE
Is Bash really required for hooks?

### ISSUE THREAD

**Issue by newtack** [buildkite/docs#526]
Can I use another executable program, e.g. Go script*, typescript (with shebang indicating ts-node), or even compiled program, as long as it is directly executable, or do I have to use bash?

* https://blog.cloudflare.com/using-go-as-a-scripting-language-in-linux/

**Comment by lox** [comment]
Presently shell script or windows batch is required because we inject some code to allow us to capture exported environment variables. 

If you didn't care too much about capturing exported environment variables, it would be possible to use anything executable I believe!

**Comment by newtack** [comment]
Thanks!

Out of curiosity: Why inject environment variables, why not set it before calling the script? If that were done/possible, we could use any script/executable.

**Comment by lox** [comment]
@newtack the issue is extracting exported environment variables not injecting them! We figure out what variables a script exports and make them available to subsequent hooks.
