### ISSUE TITLE
Kubernetes + buildkite-agent - mounting docker binary as volume doesn't seem to work

### ISSUE THREAD

**Issue by LightAndLight** [buildkite/docs#534]
The documentation at https://buildkite.com/docs/agent/v3/gcloud says to add the docker binary as a volume, but I've found that this doesn't work (it causes a segfault when trying to run docker in the pod). I could only get my deployment to work when I *removed* the `docker-binary` volume.

I also found that [buildkite/charts](https://github.com/buildkite/charts/blob/36f0a1fbfdc68347ce71e3ead5f54eb99d1bfb19/stable/agent/templates/deployment.yaml#L72) also doesn't mount the binary; only the socket.

[One of the top results on google](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) also recommends against bind-mounting the binary, since it might be unstable.

Are the docs out of date?

**Comment by harrietgrace** [comment]
Hey @LightAndLight, it definitely looks like our GCP Agent docs need an update! Thanks for letting us know 🙏🏻 I'll leave this issue open until I get it updated with our up-to-date recommendations. 

Did you get everything working okay? If you've run into any trouble, or have questions about anything, shoot us through an email to support@buildkite.com and we can help get things sorted 😊

**Comment by LightAndLight** [comment]
Thanks for the update :smile: it's all chugging along nicely now.
