### ISSUE TITLE
Trigger build with values coming from metadata

### ISSUE THREAD

**Issue by guilherme** [buildkite/docs#595]
Hello,

I have a build with a block step, which has a multi select prompt, that unlocks a [trigger step](https://buildkite.com/docs/pipelines/trigger-step).

I want to know how can I send in the trigger the value selected in the multi-select prompt?

Thank you,

**Comment by harrietgrace** [comment]
Hey @guilherme, sorry for the delay getting back to you - we've only had a skeleton crew over the holiday break. 

Great question! This one comes up pretty frequently actually, so I've started adding a new section about it to the docs. I've put some code samples and sketched out the steps to get your block step data into a trigger step in the draft PR over here: https://github.com/buildkite/docs/pull/597

In answer to your actual question - you'll need to move your trigger step from your pipeline into a script. That script will dynamically upload the step once the block step has completed. Unfortunately, we don't yet have the ability to do meta-data interpolation at runtime, but it's often requested, so hopefully sometime in the future!

There's a staging app you can have a look at too, sorry in advance that the docs aren't at all neat yet! https://buildkite-docs-review-pr-597.herokuapp.com/docs/pipelines/block-step#using-block-step-data-in-subsequent-steps I'll be getting it tidied up this week 👍🏻

Let me know if you have any other questions 😊You're also welcome to shoot an email through to [support@buildkite.com](mailto:support@buildkite.com), that inbox is staffed by our engineering team 💖

**Comment by harrietgrace** [comment]
This docs update is now live 😊You can find it at the end of the Block Step page:  https://buildkite.com/docs/pipelines/block-step#passing-block-step-data-to-other-steps
