### ISSUE TITLE
"label:" vs "name:"

### ISSUE THREAD

**Issue by JensRantil** [buildkite/docs#60]
When I export a pipeline it says "label:" on the steps. https://buildkite.com/docs/guides/uploading-pipelines has something that says "name:", but never mentions "label:". Are they the same? Is there reference documentation for this somewhere?

**Comment by keithpitt** [comment]
@JensRantil oh! They're both the same thing, one `name` is an alias for `label` - but we prefer `label`. I'll get those docs updated now :)

**Comment by keithpitt** [comment]
This is fixed and deployed now - thanks for letting us know! 🚀
