### ISSUE TITLE
Doc example is causing parsing troubles. ":pipeline:" in label

### ISSUE THREAD

**Issue by ianbrex** [buildkite/docs#600]
I was following steps in the documentation
https://buildkite.com/docs/pipelines/defining-steps

```
steps:
  - command: .buildkite/pipeline.sh | buildkite-agent pipeline upload
    label: :pipeline: Upload
  - wait
```

I was getting error

```
2020-01-10 19:28:45 FATAL  Pipeline parsing of "pipeline.yml" failed (Failed to parse pipeline.yml: line 2: mapping values are not allowed in this context)
--
  | 🚨 Error: The command exited with status 1
```

As soon as I removed ":pipeline:" from label and changed it to
`   label: Upload`
it started working properly.

I was wondering if this is a bug in a code or in documentation? For now simple fix would be to remove ":pipeline:" from documentation.

**Comment by harrietgrace** [comment]
Hey @ianbrex! Sorry you ran into that error, and thanks for letting us know. It looks like the example is missing some quotes 😬I'll add those to the docs 👍🏻

With quotes around the label text, the emoji renders properly and the error goes away:

```
steps:
  - command: .buildkite/pipeline.sh | buildkite-agent pipeline upload
    label: ":pipeline: Upload"
```

![image](https://user-images.githubusercontent.com/2074469/72227681-d7ad3800-35f3-11ea-9ec1-96afc29d4139.png)
