### ISSUE TITLE
Configure plugin versions (and perhaps other options) in one place

### ISSUE THREAD

**Issue by twometresteve** [buildkite/docs#618]
We have some pipeline that use the same plugin several times.  We lock each to a version, as recommended, but this leads to a lot of duplication and unnecessary noise in the yml file.

Would it be possible to introduce a mechanism for specifying the versions (and perhaps other configuration parameters) of plugins in a single location in the yml file?  I suppose I'm thinking of something along the line of a Maven pluginManagement sections.

Many thanks,
2m Steve.

**Comment by harrietgrace** [comment]
@twometresteve super cool suggestion! Sorry for the delay getting back to you about this 😔I'll bring it up with the team and see what we can come up with 🤓I'll leave this issue open until we figure something out.

**Comment by plaindocs** [comment]
I'm closing this for now, will document changes to the plugin system as they happen.
