### ISSUE TITLE
pre-exit hook runs after every command?

### ISSUE THREAD

**Issue by xibz** [buildkite/docs#619]
We have a pre-exit hook under `.buildkite/hooks/pre-exit`. Based on the documentation it should run after the job is finished. However, that isn't what is happening, and is instead running after each command

`running local pre-exit hook`

This doesn't seem correct, unless I am misunderstanding the documentation.

edit: Also, don't know if this is the best place to create this issue.

**Comment by harrietgrace** [comment]
Hey @xibz, I'm sorry for the delay getting back to you about this, are you still seeing the `pre-exit` hook running at the wrong time? If so, could you shoot through an email to support@buildkite.com with the details from this issue, and we can take a look at one of the builds you're seeing the behaviour in. 

I'm going to close this issue for now, but feel free to reopen it if you've got any other questions.
