### ISSUE TITLE
no-ssh-keyscan vs no-automatic-ssh-fingerprint-verification

### ISSUE THREAD

**Issue by k----n** [buildkite/docs#625]
Are they the same settings?

In config there is: no-automatic-ssh-fingerprint-verification
In the docs (https://buildkite.com/docs/agent/v3/securing) there is: no-ssh-keyscan

**Comment by harrietgrace** [comment]
Hey @k----n, only `no-ssh-keyscan` in available from v3.0.0 of the agent. 

The old config item `no-automatic-ssh-fingerprint-verification` was [renamed](https://github.com/buildkite/agent/pull/671) to `no-ssh-keyscan` prior to v3 being released 😊

The old one is still around, but hidden. It's [deprecated](https://buildkite.com/docs/agent/v3/configuration#deprecated-configuration-settings) and will likely be removed in v4.
