### ISSUE TITLE
Cannot update pipeline steps via REST API

### ISSUE THREAD

**Issue by ericberic** [buildkite/docs#628]
Hey there, it looks like updating "steps" via REST API returns HTTP OK, however, the backend ignores the update. To reproduce, create a pipeline via the web UI, define some steps, then:
```
curl -H "Authorization: Bearer $TOKEN" -X PATCH "https://api.buildkite.com/v2/organizations/${YOUR_ORG}/pipelines/${YOUR_PIPELINE}" -d '{"steps":[{"type":"script","command":"echo hello"}]}'
```
The steps field remain unchanged in spite of the HTTP OK response. I'm expecting steps to change.

**Comment by robbalmbra** [comment]
Im having the exact same issue, nothing is updated within the pipeline, and it returns the unchanged yaml. Please help
