### ISSUE TITLE
buildkite-agent meta-data set --job doc is misleading

### ISSUE THREAD

**Issue by dws-uber** [buildkite/docs#631]
The documentation on https://buildkite.com/docs/agent/v3/cli-meta-data#setting-data states:

     --job value                 Which job should the meta-data be set on [$BUILDKITE_JOB_ID]

However, based on the output from https://buildkite.com/docs/apis/rest-api/builds#list-builds-for-a-pipeline what I am seeing is that the meta-data is set on the build, not the job.  If `--job` is intended only to identify the *build* where the meta-data will be set, it would be great if the documentation described this better.  (What I really want is per-job meta-data, but that's a separate issue.)

**Comment by yob** [comment]
Thanks @dws-uber.

That help text comes from the agent binary, so I've proposed an update there. Once that merges, we can update the docs.

**Comment by harrietgrace** [comment]
Docs updated! 🙌🏻🌈
