### ISSUE TITLE
Gitlab docs are broken

### ISSUE THREAD

**Issue by lox** [buildkite/docs#64]
Just signed up for https://githost.io/, trying to get it integrated with BK. Have run into some issues, would certainly be good to get it mentioned on here https://buildkite.com/docs/how-tos/gitlab

**Comment by harrietgrace** [comment]
Hey! Thanks for letting us know 😄 What were the specific issues that you found? It would be cool to have a section on troubleshooting for common problems 👍🏻

**Comment by lox** [comment]
First off it would be good to mention Githost as an option on the page, beyond that I currently have a support ticket open with them about an issue where the Buildkite service doesn't seem to be contactable from Gitlab.

**Comment by lox** [comment]
It looks like the events needed are incorrect, I'm currently working with @keithpitt and the Gitlab peeps to figure out how to actually make this work.

Some more detail here https://gitlab.com/gitlab-com/support-forum/issues/837#note_18623444

**Comment by lox** [comment]
Ok, looks like the description of what needs to be checked in the webhook is wrong too. It should be only push events:

![](https://lachlan.me/s/EUfjaet1.png)

**Comment by lox** [comment]
It's also very easy to not copy-paste the whole value in here, because it has a colon in the middle. Double clicking the field will select up to the colon, which will half-work, but fail later.

![](https://lachlan.me/s/fPiu5ct5.png)

**Comment by harrietgrace** [comment]
Thanks a bunch for all the info! Just updated the gitlab setup doc to have the correct webhook info, and to have easily selectable fields rather than text boxes 🎉  

Docs about Githost specifically have been added to the To Do list 🙂

**Comment by blakestoddard** [comment]
Random drive-by: Out of curiosity, what is the reasoning behind only choosing to have Gitlab post to the webhook URL for just pushes? The GitHub docs also suggest doing them for pushes, pull requests, and deploys:
<img width="748" alt="screenshot 2016-12-27 09 58 29" src="https://cloud.githubusercontent.com/assets/7963833/21504320/0f760f6e-cc1b-11e6-8673-2a1945e9c927.png">

**Comment by lox** [comment]
Excellent drive by, I'd initially misunderstood this and so provided the
wrong feedback. Had been meaning to follow up.

The "service" part provides most of the events, apparently excluding "merge
requests", which is why the additional webhook is needed.

So my suggestions were basically completely wrong 😱

**Comment by keithpitt** [comment]
@blakestoddard yeah, you'd think it'd be the same, but GitLab was pretty broken internally when we first did our integration, which is why we needed to do the 2 part thing :(

We've been meaning to get back around to cleaning it all up, but it's not high on our list at the moment (since it kinda works, but a bit yucky) Thanks for the drive-by though!

**Comment by harrietgrace** [comment]
Updated the Gitlab docs again to reflect their new UI. 

@blakestoddard @lox I'm going to close this issue, but you're welcome to re-open if you need to. Docs additions for Githost are on our to-do list, as are updates to our Gitlab webhook event support.
