### ISSUE TITLE
Filename for codeblock syntax

### ISSUE THREAD

**Issue by plaindocs** [buildkite/docs#666]
By default Markdown doesn't have a way a way to specify the filename for a codeblock.

Kramdown allows for specifying arbitrary attributes using `{: attribute="value"}`.

````md

```
READ ME
```
{: codeblock-file="README.md"}
````

And there is some discussion about adding something similar to CommonMark if we're intending to move towards that https://talk.commonmark.org/t/consistent-attribute-syntax/272

Seems good enough unless there is a good reason to use something else. 

Then it is a case of using that info to show the info in a useful manner.  `Prism.js` has some chat here, https://github.com/PrismJS/prism/issues/910 and here https://prismjs.com/plugins/show-language/ .  but I've not really found anything similar for Pygments.

```
filename
    A string used to generate a filename when rendering <pre> blocks, for example if displaying source code.
```

Seems relevant. https://pygments.org/docs/formatters/

And here is an example of how it can look (with a darker code block) 
![image](https://user-images.githubusercontent.com/95874/77162290-3a4a0680-6a71-11ea-89f8-976a38cbdfd8.png)

@toolmantim does this look doable?
@harrietgrace any thoughts?

**Comment by toolmantim** [comment]
Yep, totally doable! Love it. Won't be in time for plugins directory launch, but we can add this soon.
