### ISSUE TITLE
Detect submodule?

### ISSUE THREAD

**Issue by plaindocs** [buildkite/docs#668]
If you  run `rails server` without `git submodule update --init` things break.

Checking for an empty `vendor/emojis` should do the trick I think. Not quuuite sure where to put it. The dev environment intializer?

**Comment by harrietgrace** [comment]
Is this when you're first setting things up for dev? Or in an ongoing way? The init bit is in the readme of this repo, does it need to go somewhere else too?

**Comment by plaindocs** [comment]
Yeah, I mean as part of the `Rakefile` or something so that when when you re-clone the repo and forget to intialize  the submodule (for example :-p) you an error message that makes more sense. But the audience here is pretty much just me I think.

**Comment by harrietgrace** [comment]
That sounds like a great addition! I've no idea where's a good place to add that though 🤔@yob any ideas on where's a good spot for that in the current setup?

**Comment by plaindocs** [comment]
Overall doesn't make much sense to spend any time on this.
