### ISSUE TITLE
Rebuilding a cancelled job gets Forbidden even when the API access token has full permissions

### ISSUE THREAD

**Issue by HariSekhon** [buildkite/docs#689]
Hi,

When trying to trigger a retry of a build, I get a Forbidden result even though the access token has full permissions and succeeds in all other calls:
```
curl -sSH 'Accept: application/json' \
-H 'Authorization: Bearer <token>' \
https://api.buildkite.com/v2/organizations/hari-sekhon/pipelines/devops-perl-tools/builds/17/rebuild \
-X PUT
{
  "message": "Forbidden"
}
```
The token's permissions are shown below:
<img width="871" alt="Screenshot 2020-04-01 at 19 20 27" src="https://user-images.githubusercontent.com/2211051/78172404-e74b5880-744d-11ea-84bd-56ccc8a3502f.png">

**Comment by HariSekhon** [comment]
Looks like this might be a generic problem as I have another script that is doing this and it also fails, even though that script was saved after working in another environment with another token, but I cannot see why the token doesn't permit this looking at the screenshot of the token's permissions above:

```
curl https://api.buildkite.com/v2/organizations/hari-sekhon/pipelines/devops-python-tools/builds \
-H 'Authorization: Bearer <same_token>' \
-X POST \
-F commit=HEAD \
-F branch=master \
-F 'message=triggered by Hari Sekhon buildkite_trigger.sh script'
{
  "message": "Forbidden"
}

```

**Comment by harrietgrace** [comment]
Hey @HariSekhon, sorry to hear you've run into those errors 😔Could you please send through an email to support@buildkite.com? You can link back to this issue if you don't want to repeat all your examples and such 😊
