### ISSUE TITLE
Regex on branch filters

### ISSUE THREAD

**Issue by caarlos0** [buildkite/docs#699]
On the branch filter, I wanted to match, for instance, `2.4.1`, but not `2.4.1-something`.

I tried putting a regex there but it seems it doesn't work.

Is there another way?

**Comment by harrietgrace** [comment]
Hey @caarlos0! Ah yeah, sorry you ran into that 😞Are you doing your filtering at a pipeline level or on a step? 

If you're using filtering at a step level, you can use [conditionals](https://buildkite.com/docs/pipelines/conditionals) which support regex.

**Comment by caarlos0** [comment]
Hey! I tried on the github branch limiting UI:

![image](https://user-images.githubusercontent.com/245435/78789417-82c75680-7983-11ea-839f-a38e6cfc51dd.png)

the `*` seems to work, but its not the same thing as the regex I tried (`/\d+\.\d+\.\d+/`). 

> If you're using filtering at a step level, you can use [conditionals](https://buildkite.com/docs/pipelines/conditionals) which support regex.

hmm looks like a good option too... thanks 🙏

**Comment by plaindocs** [comment]
It looks to me like a note in [Branch Configuration](https://buildkite.com/docs/pipelines/branch-configuration) making it more explicit that you can only use `*` wildcards and `!` negation in pipeline level filters might be helpful here, along with a couple of examples of when you want to might use conditionals, such as this one.
