### ISSUE TITLE
start multiple agents with different config on macOS reboot ( startup )

### ISSUE THREAD

**Issue by patrick-tresp** [buildkite/docs#730]
i stumbled over this documentation to start multiple agents on linux system.
- https://buildkite.com/docs/agent/v3/ubuntu#running-multiple-agents
i am running a macOS machine to start 4 agents with different tags manually now.

The documentation of macOS does not include this info, the config file seems to be made for 1 agent and not for multiple.

is there any approach to also start multiple agents on startup on macOS?

i only see one config file solution … 

Thanks for any best practices on this,

Patrick

**Comment by harrietgrace** [comment]
Hey @patrick-tresp, sorry for the delay getting back to you. Did you end up sorting out your macOS agents, or are you still looking for some examples? 

There are two different ways you can get going with multiple agents, both using the `launchd` service. The quickest way is to edit the agent's plist to include a `--spawn` flag with the number of agents you need. However, if you need different config for each agent, you can duplicate the plist and change the config for each one. 

I've just started a PR to add a section about running multiple agents to the macOS installation guide 👍🏻I'll leave this issue open until that's merged 😊

**Comment by patrick-tresp** [comment]
oh thanks for the support and enhancing the docs! i love it!
