### ISSUE TITLE
buildkite agent windows installation script env variables

### ISSUE THREAD

**Issue by metaflow** [buildkite/docs#735]
I wonder why https://raw.githubusercontent.com/buildkite/agent/master/install.ps1 is using variable names `buildkiteAgentToken`, `buildkiteAgentTags` etc. that are different from the screaming snake convention in https://buildkite.com/docs/agent/v3/configuration ?

In my use case I have already configured all parameters via environment "BUILDKITE_..." variables and want to install and start an agent from a script.

I can update this in the installation script if you don't mind. Or maybe script should be tolerant to missing parameters.

**Comment by lox** [comment]
Darn good question. I was still trying to figure out windows conventions. I drew a lot of inspiration from the docker windows installer which used those conventions. I must admit that my knowledge of windows scripting best practices is limited!

**Comment by metaflow** [comment]
@lox do you think it worth to update variables to match other places? I can do that

**Comment by plaindocs** [comment]
@lox if you end up making any changes to the agent please reopen.
