### ISSUE TITLE
Clarify/Detail how Hook scripts are handled

### ISSUE THREAD

**Issue by DWSR** [buildkite/docs#758]
The current documentation on hooks has the following in it:

> Hooks are bash scripts you can use to execute commands and export environment variables. All the standard Buildkite environment variables are available to be used inside your hook scripts.

IMO, this is ambiguous since most people (myself included!) would assume that this means that Buildkite simply executes the hook script, which is not at all how it works. The current process, as I understand it, is:

1. The agent copies the script to `$TMPDIR`
1. The agent sources the script with the configured shell (by default `/bin/bash`)
1. The agent injects some code before and after to help determine the value of environment variables
1. The agent finally "executes" the script

The above are very important to know for the following reasons (among others):

* Trying to call other scripts relative to the hook script will not work as expected (e.g. `$0` is the temporary copy of the script, whereas `$BASH_SOURCE` is the location of the original script)
* The shebang line will be entirely ignored. In Bash this probably doesn't matter that much since the shell's behaviour is configured almost exclusively with `set` statements, but other shells (notably `ash` which is the default on Alpine Linux) use and support parameters passed in the shebang (e.g. `#!/bin/sh -eux`)
* The agent might source the script using a different shell than the script was written in (e.g. on Alpine the default shell is `/bin/sh`, whereas the script might be interpreted with `/bin/bash` _without_ its `sh`-compatible mode enabled)
* Supporting hooks written in other languages (such as Python or Ruby) requires using the hook script as an entrypoint (e.g. https://github.com/buildkite/agent/issues/1136#issuecomment-563901017)

I think the documentation should be updated to clarify and detail exactly how hooks are handled and why this is so. A quick search of the `buildkite/agent` repo shows a number of issues that are raised due to the lack of clarity in the documentation.

**Comment by plaindocs** [comment]
Hi @DWSR thanks for the super detailed report. I'll update the docs with some clarifications.

**Comment by plaindocs** [comment]
I think that PR addresses most of your suggestions. Please let me know if you have further suggestions.

**Comment by DWSR** [comment]
@plaindocs Left some comments on the PR
