### ISSUE TITLE
Add caveat to webhook payload section

### ISSUE THREAD

**Issue by niceking** [buildkite/docs#771]
Hello! Can we add a caveat to [this section](https://buildkite.com/docs/apis/webhooks#http-request-body) about the http request body, as the request body may represent a later version of the object than the one that triggered the event. This is in response to a customer query, in [this slack thread](https://buildkite.slack.com/archives/CNVQX96R5/p1594357192080100).

**Comment by plaindocs** [comment]
Fixed in #926
