### ISSUE TITLE
Add workaround for BuildKit logs 

### ISSUE THREAD

**Issue by niceking** [buildkite/docs#773]
Docker BuildKit's logs don't get automatically collapsed into headings, customer has found a workaround, details in [here](https://secure.helpscout.net/conversation/1220096047/10950?folderId=1113725)

Could add to the docs [here?](https://buildkite.com/docs/pipelines/managing-log-output)

**Comment by plaindocs** [comment]
More work needed on the workaround before we can document it, closing for now.
