### ISSUE TITLE
Document using unstable and experimental agent installer options

### ISSUE THREAD

**Issue by niceking** [buildkite/docs#774]
On this page [here](https://buildkite.com/docs/agent/v3/ubuntu), the user can also install the beta version of the agent by specifying 'unstable' instead of 'stable', and install master by specifying 'expermimental'.

**Comment by plaindocs** [comment]
This apply to v3 installations generally, right? Not just Ubuntu.

**Comment by niceking** [comment]
Hmm not sure how the agent gets packaged and released onto the various package managers!! It looks like it should work for Ubuntu and Debian at least, but dunno about other OS. Perhaps @toolmantim or @jayco knows more about this?

**Comment by toolmantim** [comment]
The specific names/labels/technique might be different between the types of installers, but I believe that all of them have a way to switch between stable releases, beta releases, and main build releases.
