### ISSUE TITLE
Screenshot of Github webhook permissions is out of date

### ISSUE THREAD

**Issue by lox** [buildkite/docs#78]
E.g https://buildkite.com/macstadium/vmkite-images/settings/setup/github

New ones look like this: ![](https://lachlan.me/s/opPqImek.png)

**Comment by harrietgrace** [comment]
Thanks @lox! Will update 👌🏻

**Comment by harrietgrace** [comment]
@lox looks like this has been updated 🎉 Closing this for now, but if you find it needs updating again you're welcome to re-open 😊
