### ISSUE TITLE
can i not specify an agent "globally" in a buildkite file?

### ISSUE THREAD

**Issue by g4z** [buildkite/docs#783]
the buildkite config file below specifies the agent "globally", which you would think would apply to all the steps.

what actually happens is the the first step will always run on agent `deploy-server-1`, but the second step could run on any of our pool of agents.

the intention is that all steps in this config should run on `deploy-server-1`. 

if the second step runs quickly (ie. i enter the version and click unblock within a few seconds), the second step will (~99% of the time) run on the same agent as the first step. If i'm slower at starting the second step, there seems to be a higher chance it runs on some random other agent.

i know now that i can specify the agent for each step, but this seems kind of clunky.

perhaps i missed the documentation about this, or perhaps it's a bug.

example config...

    agents:
      type: deploy-server-1

    steps:
      - block: "Version to deploy"
        fields:
          - text: "Version"
            key: "deploy-version"
            hint: "Enter the version to deploy (eg. v1.0)"
            required: true

      - block: "Confirm deploy to production"

      - label: "Deploy to production"
        timeout_in_minutes: 10
        commands:
          - "DEPLOY_VERSION=$(buildkite-agent meta-data get deploy-version) make deploy"

thanks for any info!

regards

**Comment by jayco** [comment]
Hey @g4z sorry for the late reply!

The block steps themselves don't run on agents, but the command step does. If you are still experiencing issues around this, would you like to send us through a message with the build details to support@buildkite.com and we can check it out for you?
