### ISSUE TITLE
Document SSO migration

### ISSUE THREAD

**Issue by sj26** [buildkite/docs#787]
It'd be nice to document how to migrate from one SSO provider to another, especially when emails don't match. i.e. if a company changes domains, how to advise users to add the new email address to their user account, or how to link their existing account when signing in via the new provider. Does that make sense? It seems to come up often enough in support that having documentation available might make sense.

**Comment by ramtin2020** [comment]
> It'd be nice to document how to migrate from one SSO provider to another, especially when emails don't match. i.e. if a company changes domains, how to advise users to add the new email address to their user account, or how to link their existing account when signing in via the new provider. Does that make sense? It seems to come up often enough in support that having documentation available might make sense.

**Comment by plaindocs** [comment]
Hey @karensawrey -> I found some more info, looks like the trickier stuff is when you change domains as well as providers.

1. You may need to update your SSO configuration in your IdP to reference your new organization name
2. We don't do any sort of redirection from the old to the new org name, so any existing links will break
3. Any custom scripts you have that reference the existing organization name will need to change

**Comment by karensawrey** [comment]
> Hey @karensawrey -> I found some more info, looks like the trickier stuff is when you change domains as well as providers.
> 
> 1. You may need to update your SSO configuration in your IdP to reference your new organization name
> 2. We don't do any sort of redirection from the old to the new org name, so any existing links will break
> 3. Any custom scripts you have that reference the existing organization name will need to change

Aha, so it's indeed trickier than is currently implied in the docs. Will add the migration piece accordingly. Thanks, @plaindocs!

**Comment by sj26** [comment]
@plaindocs that sounds like renaming an organization? I think that's a separate thing?

**Comment by plaindocs** [comment]
Well, @sj26 what was your original intent? I thought docs on both migrating from one provider to another, and migrating from one provider to another on a new domain? Or do you mean that just the stuff I pasted in is from renaming?

**Comment by sj26** [comment]
The scenario that most often comes up in support is, roughly:

I am the admin of an organization within Buildkite. We have an SSO provider set up. We want to change SSO providers. How do I add a new provider? Will this impact the current provider? Will users need to sign up again, or can they use the same account? When can I safely remove the old provider? I might be changing the email domain, but usually not.

**Comment by karensawrey** [comment]
Looks like the procedure is clear now, that's enough for me to be able to describe the migration nicely. Thank you @plaindocs and @sj26 for getting to the very soul of the issue and providing the info!

**Comment by plaindocs** [comment]
Being worked on in #934
