### ISSUE TITLE
Hooks that export variables or change directories should not have a #!/bin/bash line.

### ISSUE THREAD

**Issue by jeffreyctang** [buildkite/docs#79]
I'm looking at: 
https://buildkite.com/docs/agent/hooks

An example hook is given as:

    #!/bin/bash
    set -eu
    echo '--- :house_with_garden: Setting up the environment'
    export GITHUB_RELEASE_ACCESS_KEY='xxx'

The first line  "#!/bin/bash"  implies this is a script which will get executed.   If it is executed, the export won't do anything.     A similar issue exists with the  pre-command hook.
It's a small picky issue, but caused me some confusion and extra work when someone asked me to create an env hook.

**Comment by mvines** [comment]
👍 I was briefly confused by this as well.  These scripts are `source`ed so the shebangs should be removed.

**Comment by toolmantim** [comment]
This is a good point, and thanks for creating the issue.

We should state that these bash scripts are sourced in a code comment up the top, and do the same in the sample hook files that are included in the distros too.

Will fix!
