### ISSUE TITLE
Can we get an exhaustive guide to the pipeline file structure?

### ISSUE THREAD

**Issue by piotrb** [buildkite/docs#81]
It seems parts of the docs are scattered all over the place with big chunks missing

I can see definition of the main keys in a step, then followed by the main plugins and what they can do, and what the different parameters are.

**Comment by harrietgrace** [comment]
Good news, this is actually already in progress here: https://github.com/buildkite/docs/pull/76 🎉

That PR should be out pretty soon. If there's anything else about the pipeline.yml that you'd like to see added after that, add it to this issue 🙂

**Comment by harrietgrace** [comment]
#76 is now live here: https://buildkite.com/docs/pipelines/command-step
