### ISSUE TITLE
Proper way to handle node_modules across steps?

### ISSUE THREAD

**Issue by Akkuma** [buildkite/docs#83]
My company is tarring up the node_modules and uploading this as an artifact. We then have to check in each build step if a node_modules exists and if not to download the artifact & untar it. None of the examples presented are even close to real world, since 1 step isn't close to how people use CI, which makes it quite difficult to understand whether this is the proper way to handle it.

**Comment by ticky** [comment]
Tarring as an artefact is the way to do it if you’re not using docker!

This part of the setup is definitely something we hope to address in upcoming docs improvements!

**Comment by lox** [comment]
I'm going to close this one in favour of the more general #177.
