### ISSUE TITLE
Environment variables and interpolation

### ISSUE THREAD

**Issue by tnh** [buildkite/docs#84]
Hi peeps

I'm a little confused about the environment variables & interpolation logic. For example - 
```
env: 
  A: 'somevar'
steps;
  - name: 'test'
  env:
    A: 'anothervar'
```
and I fire a build and set an environment within the build of 
` A=foobar`

What does `$A` result in?

It appears that the result is `A=foobar`. 
It seems the logic is the environment within a step, and then the global environment set within a pipeline. Any pass through environment variables that are set are ignored if there is a global environment set within the pipeline.yml

**Comment by harrietgrace** [comment]
Hey @tnh! Only 18 months late (😱I'm so sorry), but I added some info to the docs about how the environment variables precedence works 🎉 It's here if you want to check it out: https://buildkite.com/docs/builds/environment-variables#environment-variable-precedence

I'd be keen to hear what you think, and if it answers your original question 😊
