### ISSUE TITLE
Consequences of deleting a user

### ISSUE THREAD

**Issue by petervtzand** [buildkite/docs#85]
Hi,

Just to be sure. We've had a member in our organization who set up the most of our buildkite environment. Now that he has left the organization I want to delete him from the users. What are the consequences of this? I previously had some bad experiences where deleting a user, automatically deleted all the things that he had set up for us.

Bye, Peter

**Comment by sj26** [comment]
Hi Peter!

Buildkite never deletes users per se. You can remove them from your organization, though. Nothing will be deleted or removed from the account except the user themselves.

The only potential gotcha is you need to make sure that at least one other user still in your account has [connected their Buildkite user account to GitHub](https://buildkite.com/user/connected-apps) so we can still mark your git commits as passing or failing.

Send us an email to support@buildkite.com if you do hit any issues.

Thanks!
Sam.

**Comment by sj26** [comment]
Ah, sorry I missed a bit! 😅

API Access Tokens are bound to users. If they setup anything talking to the [Buildkite REST API](https://buildkite.com/docs/rest-api) then those tokens will stop being able to operate on anything in your organization after removal. This may be relevant if you're using the [elastic-ci-stack-for-aws](https://buildkite.com/docs/quickstart/elastic-ci-stack-aws), you'll need to replace the access token it uses for metrics.

If you can't speak to the member you'd like to remove please reach out to use via support@buildkite.com and we can double check for you.
