### ISSUE TITLE
Edit pipeline example doesn't work

### ISSUE THREAD

**Issue by charleskawczynski** [buildkite/docs#861]
Using the suggested [YAML](https://buildkite.com/docs/pipelines/defining-steps#adding-steps-pipeline-dot-yml-file) script in the "edit steps" does not work and results in the error `buildkite Failed to parse YAML: line 1: did not find expected key`.

**Comment by plaindocs** [comment]
Hi @charleskawczynski 

Does `.buildkite/pipeline.yml` exist? 

> this step will look for a directory called `.buildkite` containing a file named `pipeline.yml`.

Either way I'll take a look at the wording of that page and see what I can improve.

**Comment by charleskawczynski** [comment]
I tried using
```
steps:
  - label: "<img class="emoji" title="pipeline" alt=":pipeline:" src="https://buildkiteassets.com/emojis/img-buildkite-64/pipeline.png" draggable="false" /> Pipeline upload"
    command: buildkite-agent pipeline upload
```
and I suspect I ran into [this](https://github.com/ruby/psych/issues/190#issuecomment-162658663), but I couldn't find where things were going wrong. I ended up just using
```
steps:
 - command: "buildkite-agent pipeline upload"
```
which worked

**Comment by plaindocs** [comment]
I've looked a bit further, and it seems there was a mistaken substitution in the label emoji.

```yaml
steps:
  - label: ":pipeline: Pipeline upload"
    command: buildkite-agent pipeline upload
```
It'll work. I've updated the docs in #863
