### ISSUE TITLE
Fix headings for troubleshooting notes

### ISSUE THREAD

**Issue by plaindocs** [buildkite/docs#878]
Hey @scopegate we currently use `h1` for all of our troubleshooting notes which doesn't seem right:

```
<div class="Docs__troubleshooting-note">
<h1>depends_on and block/wait</h1>
<p>Note that a step with an explicit dependency specified with the <code>depends_on</code> attribute will run immediately after the dependency step has completed, without waiting for <code>block</code> or <code>wait</code> steps unless those are also explicit dependencies.</p>
</div>
```

What is the best way to give this a title which isn't outside of the doc structure? Just `p id="title"` ?

**Comment by scopegate** [comment]
Good pickup @plaindocs! It'd be good to keep them as a header of some sort, so that the page can be scanned/indexed appropriately — the PR I've just linked should switch them all over to H3s, but I've left the H1 styles in place for now in case there are any stray ones I've missed.
