### ISSUE TITLE
Missing image in quickstart/getting-started

### ISSUE THREAD

**Issue by yeradis** [buildkite/docs#88]
There is a missing image at https://buildkite.com/docs/quickstart/getting-started

Specifically `email-address.png` is missing, the one reference here:
```
<%= image "email-address.png", size: "251x52", alt: "Screenshot of email address section of Buildkite settings" %>
```
https://github.com/buildkite/docs/blob/master/pages/quickstart/getting_started.md.erb#L25

**Comment by harrietgrace** [comment]
Thanks for reporting that @yeradis! Since we launched a new feature last week to help people connect their email addresses, I don't think we even need that section of the docs anymore... If you'd like to follow updates, it's in #89 😊

**Comment by harrietgrace** [comment]
#89 is now live, section/image has been removed: https://buildkite.com/docs/quickstart/getting-started
