### ISSUE TITLE
Clarify where to find the pipeline slug 

### ISSUE THREAD

**Issue by niceking** [buildkite/docs#915]
A customer [emailed in](https://secure.helpscout.net/conversation/1406864965/15510/) as their trigger step wasn't working as they hadn't supplied the correct pipeline slug. I had a look at the [docs for trigger steps](https://buildkite.com/docs/pipelines/trigger-step) and realised it wasn't super clear on where you would find the pipeline slug!

**Comment by plaindocs** [comment]
Thanks @niceking 

![image](https://user-images.githubusercontent.com/95874/105952631-1fbdc200-6072-11eb-92c1-945b51120795.png)

@karensawrey might be a nice quick fix for you to pick up?
