### ISSUE TITLE
`buildkite-agent annotate` takes an `arguments` argument that is never explained

### ISSUE THREAD

**Issue by nickatsegment** [buildkite/docs#916]
![image](https://user-images.githubusercontent.com/40582825/106018503-94532980-608f-11eb-9570-5bfe847b7e30.png)

**Comment by plaindocs** [comment]
Hey @nickatsegment that `arguments` argument is actually a shorthand for all of the optional arguments, but I can see how that might not be clear.

I've seen `[option]`, `[OPTION...]` and even `[OPTION]...` used elsewhere. Could you raise an issue over in https://github.com/buildkite/agent/ if you think it warrants it.

**Comment by nickatsegment** [comment]
Yeah, looks a little inconsistent over there. I'll open an issue.
