### ISSUE TITLE
Clarify create_pipeline API documentation

### ISSUE THREAD

**Issue by changusmc** [buildkite/docs#947]
I migrated to YAML pipelines and was trying to use the `create_pipeline` endpoint and initially used `steps` in the body. I received a 500 HTTP response. 

The documentation should clarify that if a user has migrated to YAML pipelines, they cannot use `steps` in the body. Bonus points if the API response stated that as well.

**Comment by plaindocs** [comment]
Thanks for reporting @changusmc the docs now cover using the API to create YAML pipelines.
