### ISSUE TITLE
Pipeline-level branch filtering Pull request note

### ISSUE THREAD

**Issue by pahnev** [buildkite/docs#956]
The [documentation states](https://buildkite.com/docs/pipelines/branch-configuration#pipeline-level-branch-filtering) that Pull request would ignore branch filter.
However I'm not able to see that to be the case. I've enabled the "Build Pull Requests" in the pipeline settings, but any new PRs or commits into a PR branch don't trigger builds.
I have also experimented with this using Bitbucket server, but it's behaving the same way.

![Screenshot 2021-03-05 at 11 16 10](https://user-images.githubusercontent.com/2078494/110094339-60f96e00-7da4-11eb-94b3-e8eece4394ea.png)

### Is this documentation up to date or am I just missing something?
 
Here are my pipeline settings:

![Screenshot 2021-03-05 at 11 02 24](https://user-images.githubusercontent.com/2078494/110094102-1e379600-7da4-11eb-9f59-39f46fffa764.png)

```
steps:
  - label: "Build"
    command: "swift build -v"
    branches: "main"
```

**Comment by plaindocs** [comment]
Hey @pahnev 

This is the branch filter the docs mention, which is just above the GitHub settings you show in your screenshot. I'll add a screenshot to the docs to make this more clear.

![image](https://user-images.githubusercontent.com/95874/110124388-4fbf5a00-7dc2-11eb-8798-8401cfe1bd1e.png)

The YAML you have is a [step level](https://buildkite.com/docs/pipelines/branch-configuration#step-level-branch-filtering) filter, even though it applies to branches.

**Comment by pahnev** [comment]
Ah, completely missed that it was different filtering, since most of the docs and examples have the step level filters.
