### ISSUE TITLE
AWS SNS guide is outdated

### ISSUE THREAD

**Issue by ticky** [buildkite/docs#98]
The [AWS SNS guide](https://buildkite.com/docs/webhooks/integrations) is outdated and the linked document no longer gives enough detail to follow through with!

**Comment by harrietgrace** [comment]
Hey @ticky, I've been having a look around for a new guide to replace the one from 2015 but I'm not really sure what the important bits of the old one are! Would either of these guides suit?

https://docs.aws.amazon.com/sns/latest/dg/sns-lambda-as-subscriber.html https://docs.aws.amazon.com/lambda/latest/dg/with-sns-example.html

**Comment by ticky** [comment]
I don’t remember the context around this, sorry, should’ve added more context. I think this was related to a support thing?

**Comment by toolmantim** [comment]
(notes from @harrietgrace and I’s call)

Looking at https://buildkite.com/docs/apis/webhooks/integrations perhaps we change the header to just "AWS Lambda" and then something roughly like:

> [AWS Lambda](#) is an AWS service for running code functions in response to events. [AWS API Gateway](#) is a ... for creating HTTP endpoints for your Lambda functions. And [AWS SNS] is a messaging service which can be used to trigger many Lambda functions from webhook events.
