### ISSUE TITLE
CCMenu filtering by pipeline cannot connect

### ISSUE THREAD

**Issue by cobbce** [buildkite/docs#990]
Goal:
Connect a buildkite pipeline to ccmenu using the instructions: https://buildkite.com/docs/integrations/cc-menu

Behavior:
After generating an access token with `read_builds` scope, I am successfully able to load my organization xml:
`https://cc.buildkite.com/[organization-slug].xml?access_token=xxx`

However, I am unable to load a pipeline url, as described in the section titled `Filtering by pipeline`. Example url:
`https://cc.buildkite.com/[organization-slug]/[pipeline-slug].xml?access_token=xxx`

Things I tried:
- using the same access token with organization access and `read_builds` scope
- adding the following scopes to my existing token (in addition to read_builds): `read_organizations, read_pipelines`
- generated a new access token with all of the above. For completeness, this is org access checkbox, and the following scopes: `read_builds, read_organizations, read_pipelines`

I am sure the access token is valid because it successfully loaded the org feed. I have triple checked the url form for the pipeline feed, as copied from the example above.

Thanks!

**Comment by cobbce** [comment]
Kept noodling a bit-- I was able to load the xml from a browser, whose format seemed at a glance identical to the full org pull. But for some reason CCMenu tool itself is choking. 

Here's the xml pulled from the browser (names changed for privacy):
<Projects>
<Project name="my-pipeline" activity="Sleeping" lastBuildStatus="Failure" lastBuildLabel="89" lastBuildTime="2021-04-02T18:48:16+00:00" webUrl="https://buildkite.com/my-org/my-pipeline/builds"/>
</Projects>

Machine specs and versions:
- Macbook Pro 2019 (Intel)
- MacOS Catalina (10.15) (not Big Sur, the new one that supports Apple Silicon)
- CCMenu Version 15.0 (3B4A4B5) (installed through App Store)

**Comment by cobbce** [comment]
Any info? Just knowing it's broken would be helpful so I don't keep trying 🤣

**Comment by sj26** [comment]
Hi @cobbce! Sorry this isn't working for you. I've just tested this myself with both organization and project specific feeds and it all seems to be working. Could you send us an email with the specific organization and pipeline you're trying to add to support@buildkite.com and maybe we can dig a little deeper for you.

**Comment by cobbce** [comment]
Will do, thanks!

**Comment by cobbce** [comment]
Well, after turning it off and on again (or in this case, removing and re-adding the project) it appears to be working now. Of course I don't why my many previous efforts failed, but it's great to have everything working now. Thanks!
